//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

// ReSharper disable once CheckNamespace
namespace AOT.Launch.Localization
{
    /// <summary>
    /// LocalizationAOT 数据类（AOT 声明式多语言用，随导表生成，禁止手改）。
    /// </summary>
    public sealed class LocalizationAOT
    {
        /// <summary> ID </summary>
        public string Key { get; set; }
        /// <summary> 是否导出到代码中 </summary>
        public bool IsCode { get; set; }
        /// <summary> 简体中文 </summary>
        public string ChineseSimplified { get; set; }
        /// <summary> 繁体中文 </summary>
        public string ChineseTraditional { get; set; }
        /// <summary> 英语 </summary>
        public string English { get; set; }
        /// <summary> 日语 </summary>
        public string Japanese { get; set; }
        /// <summary> 韩语 </summary>
        public string Korean { get; set; }
        /// <summary> 泰语 </summary>
        public string Thai { get; set; }
        /// <summary> 印尼语 </summary>
        public string Indonesian { get; set; }
        /// <summary> 法语 </summary>
        public string French { get; set; }
        /// <summary> 德语 </summary>
        public string German { get; set; }
        /// <summary> 俄语 </summary>
        public string Russian { get; set; }
        /// <summary> 意大利语 </summary>
        public string Italian { get; set; }
        /// <summary> 葡萄牙语(巴西) </summary>
        public string PortugueseBrazil { get; set; }
        /// <summary> 葡萄牙语 </summary>
        public string PortuguesePortugal { get; set; }
        /// <summary> 西班牙语 </summary>
        public string Spanish { get; set; }
        /// <summary> 越南语 </summary>
        public string Vietnamese { get; set; }
    }
}