
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Hotfix.Config.Tables
{
    public sealed partial class Achievement : BeanBase
    {
        public Achievement(int Id, string Icon, string Name, string Desc, System.Collections.Generic.List<int> UnlockCondition) 
        {
            this.Id = Id;
            this.Icon = Icon;
            this.Name = Name;
            this.Desc = Desc;
            this.UnlockCondition = UnlockCondition;
            PostInit();
        }

        public Achievement(JSONNode _buf)
        {
            { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
            { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
            { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
            { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
            { var __json0 = _buf["unlock_condition"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockCondition = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  UnlockCondition.Add(__v0); }   }

            // Localization Key Begin
            Name_Localization_Key = Name;
            Desc_Localization_Key = Desc;
            // Localization Key End
            PostInit();
        }

        public static Achievement DeserializeAchievement(JSONNode _buf)
        {
            return new Tables.Achievement(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 图标
        /// </summary>
        public string Icon { private set; get; }
        /// <summary>
        /// 成就名称
        /// </summary>
        public string Name { private set; get; }
        /// <summary>
        /// 成就名称 的多语言Key
        /// </summary>
        private readonly string Name_Localization_Key;
        /// <summary>
        /// 描述信息
        /// </summary>
        public string Desc { private set; get; }
        /// <summary>
        /// 描述信息 的多语言Key
        /// </summary>
        private readonly string Desc_Localization_Key;
        /// <summary>
        /// 成就解锁条件
        /// </summary>
        public System.Collections.Generic.List<int> UnlockCondition { private set; get; }
        public const int __ID__ = -1048610522;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
            Name = translator(Name_Localization_Key, Name);
            Desc = translator(Desc_Localization_Key, Desc);
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "icon:" + Icon + ","
            + "name:" + Name + ","
            + "desc:" + Desc + ","
            + "unlockCondition:" + Luban.StringUtil.CollectionToString(UnlockCondition) + ","
            + "}";
        }

        partial void PostInit();
    }
}
