//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AOT.Launch.Localization
{
    /// <summary>
    /// 本地化多语言Key列表
    /// </summary>
    public static class L10nKey
    {
        /// <summary>
        /// 获取资源版本号
        /// </summary>
        public const string aot_get_res_version = "aot_get_res_version";

        /// <summary>
        /// 获取版本号失败，正在重试...
        /// </summary>
        public const string aot_get_res_version_fail = "aot_get_res_version_fail";

        /// <summary>
        /// 初始化资源
        /// </summary>
        public const string aot_init_res_package = "aot_init_res_package";

        /// <summary>
        /// 请求资源服务器更新配置失败，正在重试...
        /// </summary>
        public const string aot_req_remote_update_config_fail = "aot_req_remote_update_config_fail";

        /// <summary>
        /// 下载失败，正在重试...
        /// </summary>
        public const string aot_res_download_fail = "aot_res_download_fail";

        /// <summary>
        /// 资源下载中：{0}/{1}
        /// </summary>
        public const string aot_res_downloading = "aot_res_downloading";

        /// <summary>
        /// 资源加载失败，请检查网络后重启游戏!
        /// </summary>
        public const string aot_res_load_fail = "aot_res_load_fail";

        /// <summary>
        /// 正在加载配置...
        /// </summary>
        public const string aot_res_loading_config = "aot_res_loading_config";

        /// <summary>
        /// 正在加载初始化资源...
        /// </summary>
        public const string aot_res_loading_init_res = "aot_res_loading_init_res";

        /// <summary>
        /// 更新
        /// </summary>
        public const string aot_update_dialog_ok_btn = "aot_update_dialog_ok_btn";

        /// <summary>
        /// 更新资源清单
        /// </summary>
        public const string aot_update_res_manifest = "aot_update_res_manifest";

        /// <summary>
        /// 更新资源清单失败，正在重试...
        /// </summary>
        public const string aot_update_res_manifest_fail = "aot_update_res_manifest_fail";

    }
}