// <auto-generated>
//	本代码由FGUI插件CSharpAPIGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Hotfix.UI.View.Bag
{
    public partial class WinBag
    {
        public override string UIName => "WinBag";      // 界面名称
        public override string PackageName => "Bag"; // 包名
        
		private CompBagContent compContent;
		private GButton btnClose;

        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {
			compContent = (CompBagContent)GetChild("_compContent");
			btnClose = (GButton)GetChild("_btnClose");

			compContent.InitView(this);
        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {
			AddUIListener(btnClose.onClick, OnBtnCloseClick);

        }
    }
}
