//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// Localization 数据类
    /// </summary>
    public sealed partial class Localization : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = -1694250884;

        /// <summary> ID </summary>
        public string Key { private set; get; }

        /// <summary> 简体中文 </summary>
        public string ChineseSimplified { private set; get; }

        /// <summary> 繁体中文 </summary>
        public string ChineseTraditional { private set; get; }

        /// <summary> 英语 </summary>
        public string English { private set; get; }

        /// <summary> 日语 </summary>
        public string Japanese { private set; get; }

        /// <summary> 韩语 </summary>
        public string Korean { private set; get; }

        /// <summary> 泰语 </summary>
        public string Thai { private set; get; }

        /// <summary> 印尼语 </summary>
        public string Indonesian { private set; get; }

        /// <summary> 法语 </summary>
        public string French { private set; get; }

        /// <summary> 德语 </summary>
        public string German { private set; get; }

        /// <summary> 俄语 </summary>
        public string Russian { private set; get; }

        /// <summary> 意大利语 </summary>
        public string Italian { private set; get; }

        /// <summary> 葡萄牙语 </summary>
        public string PortuguesePortugal { private set; get; }

        /// <summary> 西班牙语 </summary>
        public string Spanish { private set; get; }

        /// <summary> 越南语 </summary>
        public string Vietnamese { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 Localization 实例(外部使用)
        /// </summary>
        /// <param name="key">ID</param>
        /// <param name="ChineseSimplified">简体中文</param>
        /// <param name="ChineseTraditional">繁体中文</param>
        /// <param name="English">英语</param>
        /// <param name="Japanese">日语</param>
        /// <param name="Korean">韩语</param>
        /// <param name="Thai">泰语</param>
        /// <param name="Indonesian">印尼语</param>
        /// <param name="French">法语</param>
        /// <param name="German">德语</param>
        /// <param name="Russian">俄语</param>
        /// <param name="Italian">意大利语</param>
        /// <param name="PortuguesePortugal">葡萄牙语</param>
        /// <param name="Spanish">西班牙语</param>
        /// <param name="Vietnamese">越南语</param>
        public Localization(string key, string ChineseSimplified, string ChineseTraditional, string English, string Japanese, string Korean, string Thai, string Indonesian, string French, string German, string Russian, string Italian, string PortuguesePortugal, string Spanish, string Vietnamese) 
        {
            Key = key;
            ChineseSimplified = ChineseSimplified;
            ChineseTraditional = ChineseTraditional;
            English = English;
            Japanese = Japanese;
            Korean = Korean;
            Thai = Thai;
            Indonesian = Indonesian;
            French = French;
            German = German;
            Russian = Russian;
            Italian = Italian;
            PortuguesePortugal = PortuguesePortugal;
            Spanish = Spanish;
            Vietnamese = Vietnamese;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 Localization 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private Localization(JSONNode node)
        {
            { if(!node["key"].IsString) { throw new SerializationException(); }  Key = node["key"]; }
            { if(!node["ChineseSimplified"].IsString) { throw new SerializationException(); }  ChineseSimplified = node["ChineseSimplified"]; }
            { if(!node["ChineseTraditional"].IsString) { throw new SerializationException(); }  ChineseTraditional = node["ChineseTraditional"]; }
            { if(!node["English"].IsString) { throw new SerializationException(); }  English = node["English"]; }
            { if(!node["Japanese"].IsString) { throw new SerializationException(); }  Japanese = node["Japanese"]; }
            { if(!node["Korean"].IsString) { throw new SerializationException(); }  Korean = node["Korean"]; }
            { if(!node["Thai"].IsString) { throw new SerializationException(); }  Thai = node["Thai"]; }
            { if(!node["Indonesian"].IsString) { throw new SerializationException(); }  Indonesian = node["Indonesian"]; }
            { if(!node["French"].IsString) { throw new SerializationException(); }  French = node["French"]; }
            { if(!node["German"].IsString) { throw new SerializationException(); }  German = node["German"]; }
            { if(!node["Russian"].IsString) { throw new SerializationException(); }  Russian = node["Russian"]; }
            { if(!node["Italian"].IsString) { throw new SerializationException(); }  Italian = node["Italian"]; }
            { if(!node["PortuguesePortugal"].IsString) { throw new SerializationException(); }  PortuguesePortugal = node["PortuguesePortugal"]; }
            { if(!node["Spanish"].IsString) { throw new SerializationException(); }  Spanish = node["Spanish"]; }
            { if(!node["Vietnamese"].IsString) { throw new SerializationException(); }  Vietnamese = node["Vietnamese"]; }

            // Localization Key Begin
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 Localization 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 Localization</returns>
        public static Localization DeserializeLocalization(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "key:"                + Key                + ","
                   + "ChineseSimplified:"  + ChineseSimplified  + ","
                   + "ChineseTraditional:" + ChineseTraditional + ","
                   + "English:"            + English            + ","
                   + "Japanese:"           + Japanese           + ","
                   + "Korean:"             + Korean             + ","
                   + "Thai:"               + Thai               + ","
                   + "Indonesian:"         + Indonesian         + ","
                   + "French:"             + French             + ","
                   + "German:"             + German             + ","
                   + "Russian:"            + Russian            + ","
                   + "Italian:"            + Italian            + ","
                   + "PortuguesePortugal:" + PortuguesePortugal + ","
                   + "Spanish:"            + Spanish            + ","
                   + "Vietnamese:"         + Vietnamese         + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}