
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 实体组
    /// </summary>
    public enum EEntityGroup
    {
        /// <summary>
        /// 玩家
        /// </summary>
        Player = 1,
        /// <summary>
        /// 敌人
        /// </summary>
        Enemy = 2,
        /// <summary>
        /// NPC
        /// </summary>
        NPC = 3,
        /// <summary>
        /// 道具
        /// </summary>
        Item = 4,
        /// <summary>
        /// 特效
        /// </summary>
        Effect = 5,
    }

} 

