//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 实体组
    /// </summary>
    public enum EEntityGroup
    {
        /// <summary> 玩家 </summary>
        Player = 1,

        /// <summary> 敌人 </summary>
        Enemy = 2,

        /// <summary> NPC </summary>
        NPC = 3,

        /// <summary> 道具 </summary>
        Item = 4,

        /// <summary> 特效 </summary>
        Effect = 5,
    }
}