//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 道具子类型
    /// </summary>
    public enum EItemSubType
    {
        /// <summary> 无 </summary>
        None = 0,

        /// <summary> 武器 </summary>
        Weapon = 1,

        /// <summary> 胸 </summary>
        Chest = 2,

        /// <summary> 腰带 </summary>
        Belt = 3,

        /// <summary> 鞋子 </summary>
        Boot = 4,

        /// <summary> 戒指 </summary>
        Ring = 5,
    }
}