
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 道具使用类型
    /// </summary>
    public enum EItemUseType
    {
        /// <summary>
        /// 不可使用
        /// </summary>
        CanNot = 0,
        /// <summary>
        /// 可单个使用
        /// </summary>
        UseOne = 1,
        /// <summary>
        /// 可一键全部使用
        /// </summary>
        UseTotal = 2,
    }

} 

