//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 道具类型
    /// </summary>
    public enum EItemType
    {
        /// <summary> 道具 </summary>
        Item = 1,

        /// <summary> 消耗品 </summary>
        Expendable = 2,

        /// <summary> 装备 </summary>
        Equip = 3,

        /// <summary> 碎片 </summary>
        Fragment = 4,

        /// <summary> 材料 </summary>
        Material = 5,
    }
}