//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 道具使用类型
    /// </summary>
    public enum EItemUseType
    {
        /// <summary> 不可使用 </summary>
        CanNot = 0,

        /// <summary> 可单个使用 </summary>
        UseOne = 1,

        /// <summary> 可一键全部使用 </summary>
        UseTotal = 2,
    }
}