//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 语言类型
    /// </summary>
    public enum ELanguage
    {
        /// <summary> 未指定 </summary>
        Unspecified = 0,

        /// <summary> 简体中文 </summary>
        ChineseSimplified = 1,

        /// <summary> 繁体中文 </summary>
        ChineseTraditional = 2,

        /// <summary> 英语 </summary>
        English = 3,

        /// <summary> 法语 </summary>
        French = 4,

        /// <summary> 德语 </summary>
        German = 5,

        /// <summary> 印尼语 </summary>
        Indonesian = 6,

        /// <summary> 意大利语 </summary>
        Italian = 7,

        /// <summary> 日语 </summary>
        Japanese = 8,

        /// <summary> 韩语 </summary>
        Korean = 9,

        /// <summary> 葡萄牙语(巴西) </summary>
        PortugueseBrazil = 10,

        /// <summary> 葡萄牙语(葡萄牙) </summary>
        PortuguesePortugal = 11,

        /// <summary> 俄语 </summary>
        Russian = 12,

        /// <summary> 西班牙语 </summary>
        Spanish = 13,

        /// <summary> 泰语 </summary>
        Thai = 14,

        /// <summary> 越南语 </summary>
        Vietnamese = 15,
    }
}