
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Game.Tables
{ 
    public enum EQuality
    {
        /// <summary>
        /// 白
        /// </summary>
        White = 1,
        /// <summary>
        /// 蓝
        /// </summary>
        Blue = 2,
        /// <summary>
        /// 紫
        /// </summary>
        Purple = 3,
        /// <summary>
        /// 红
        /// </summary>
        Red = 4,
        /// <summary>
        /// 橙
        /// </summary>
        Orange = 5,
    }

} 

