//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 品质
    /// </summary>
    public enum EQuality
    {
        /// <summary> 白 </summary>
        White = 1,

        /// <summary> 蓝 </summary>
        Blue = 2,

        /// <summary> 紫 </summary>
        Purple = 3,

        /// <summary> 红 </summary>
        Red = 4,

        /// <summary> 橙 </summary>
        Orange = 5,
    }
}