
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 红点显示类型
    /// </summary>
    public enum ERedDotDisplayMode
    {
        /// <summary>
        /// 只显示红点
        /// </summary>
        DotOnly = 0,
        /// <summary>
        /// 红点+数字
        /// </summary>
        DotNumber = 1,
        /// <summary>
        /// 红点数&gt;1时才显示数字，否则只显示红点
        /// </summary>
        Auto = 2,
    }

} 

