//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 红点显示类型
    /// </summary>
    public enum ERedDotDisplayMode
    {
        /// <summary> 只显示红点 </summary>
        DotOnly = 0,

        /// <summary> 红点+数字 </summary>
        DotNumber = 1,

        /// <summary> 红点数&gt;1时才显示数字，否则只显示红点 </summary>
        Auto = 2,
    }
}