
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 红点清除策略类型
    /// </summary>
    public enum ERedDotCleanStrategy
    {
        /// <summary>
        /// 手动清除(业务逻辑代码判断)
        /// </summary>
        Manual = 0,
        /// <summary>
        /// 看过自动清除
        /// </summary>
        ViewAutoClean = 1,
    }

} 

