
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Game.Config
{ 
    public enum ERedDotKey
    {
        /// <summary>
        /// 背包
        /// </summary>
        Bag = 1000,
        /// <summary>
        /// 背包.道具
        /// </summary>
        Bag_Item = 1001,
        /// <summary>
        /// 背包.技能
        /// </summary>
        Bag_Skill = 1002,
        /// <summary>
        /// 商店
        /// </summary>
        Shop = 2000,
        /// <summary>
        /// 商店.礼包
        /// </summary>
        Shop_Gift = 2001,
        /// <summary>
        /// 商店.资源
        /// </summary>
        Shop_Res = 2002,
        /// <summary>
        /// 英雄
        /// </summary>
        Hero = 3000,
        /// <summary>
        /// 英雄.装备
        /// </summary>
        Hero_Equip = 3001,
        /// <summary>
        /// 英雄.技能
        /// </summary>
        Hero_Skill = 3002,
        /// <summary>
        /// 英雄.皮肤
        /// </summary>
        Hero_Skin = 3003,
        /// <summary>
        /// 战斗
        /// </summary>
        Battle = 4000,
        /// <summary>
        /// 战斗.队伍
        /// </summary>
        Battle_Team = 4001,
    }

} 

