
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotfix.Config
{
    public enum ERedDotCleanStrategy
    {
        /// <summary>
        /// 手动清除（业务代码显式调用 ResetCount）
        /// </summary>
        Manual = 0,
        /// <summary>
        /// 框架提供 TryAutoClean，业务代码在合适时机调用（如点击页签）
        /// </summary>
        ViewAutoClean = 1,
    }
}
