//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 红点计算逻辑类型
    /// </summary>
    public enum ERedDotLogicType
    {
        /// <summary> 求和 </summary>
        Sum = 0,

        /// <summary> 任意一个即可 </summary>
        Any = 1,
    }
}