
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 红点计算逻辑类型
    /// </summary>
    public enum ERedDotLogicType
    {
        /// <summary>
        /// 求和
        /// </summary>
        Sum = 0,
        /// <summary>
        /// 任意一个即可
        /// </summary>
        Any = 1,
    }

} 

