//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 红点清除策略类型
    /// </summary>
    public enum ERedDotCleanStrategy
    {
        /// <summary> 手动清除(业务逻辑代码判断) </summary>
        Manual = 0,

        /// <summary> 看过自动清除 </summary>
        ViewAutoClean = 1,
    }
}