//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 声音组
    /// </summary>
    public enum ESoundGroup
    {
        /// <summary> 背景音乐 </summary>
        BGM = 1,

        /// <summary> 音效 </summary>
        SFX = 2,

        /// <summary> UI音效 </summary>
        UI = 3,
    }
}