
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 声音组
    /// </summary>
    public enum ESoundGroup
    {
        /// <summary>
        /// 背景音乐
        /// </summary>
        BGM = 1,
        /// <summary>
        /// 音效
        /// </summary>
        SFX = 2,
        /// <summary>
        /// UI音效
        /// </summary>
        UI = 3,
    }

} 

