
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Game.Config
{ 
    public enum EStepType
    {
        /// <summary>
        /// 无类型
        /// </summary>
        None = 0,
        /// <summary>
        /// 点击UI引导
        /// </summary>
        ClickUI = 1,
        /// <summary>
        /// 对话引导
        /// </summary>
        Dialog = 2,
        /// <summary>
        /// 等待步骤
        /// </summary>
        Wait = 3,
    }

} 

