//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// 引导步骤类型
    /// </summary>
    public enum EStepType
    {
        /// <summary> 无类型 </summary>
        None = 0,

        /// <summary> 点击UI引导 </summary>
        ClickUI = 1,

        /// <summary> 对话引导 </summary>
        Dialog = 2,

        /// <summary> 等待步骤 </summary>
        Wait = 3,
    }
}