
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Game.Config
{ 
    public enum EUILayer
    {
        /// <summary>
        /// 世界场景UI
        /// </summary>
        WorldUI = 0,
        /// <summary>
        /// 主界面
        /// </summary>
        MainUI = 1500,
        /// <summary>
        /// 一般全屏界面
        /// </summary>
        Normal = 2000,
        /// <summary>
        /// 窗口
        /// </summary>
        Window = 2500,
        /// <summary>
        /// 提示
        /// </summary>
        Tips = 3000,
        /// <summary>
        /// 引导
        /// </summary>
        Guide = 3500,
        /// <summary>
        /// 加载界面
        /// </summary>
        Loading = 4000,
    }

} 

