//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// UI界面层级
    /// </summary>
    public enum EUILayer
    {
        /// <summary> 场景UI </summary>
        SceneUI = 0,

        /// <summary> 主界面 </summary>
        MainUI = 1500,

        /// <summary> 一般全屏界面 </summary>
        Normal = 2000,

        /// <summary> 窗口 </summary>
        Window = 2500,

        /// <summary> 提示 </summary>
        Tips = 3000,

        /// <summary> 引导 </summary>
        Guide = 3500,

        /// <summary> 加载界面 </summary>
        Loading = 4000,
    }
}