//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// UI界面动画类型
    /// </summary>
    public enum EUITweenType
    {
        /// <summary> 无动画 </summary>
        None = 0,

        /// <summary> 淡入淡出 </summary>
        Fade = 1,

        /// <summary> 自定义动画 </summary>
        Custom = 2,
    }
}