
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Hotfix.Game.Config
{ 
    /// <summary>
    /// UI界面动画类型
    /// </summary>
    public enum EUITweenType
    {
        /// <summary>
        /// 无动画
        /// </summary>
        None = 0,
        /// <summary>
        /// 淡入淡出
        /// </summary>
        Fade = 1,
        /// <summary>
        /// 自定义动画
        /// </summary>
        Custom = 2,
    }

} 

