//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// LanguageDef 数据类
    /// </summary>
    public sealed partial class LanguageDef : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = 491995501;

        /// <summary> 语言 </summary>
        public ELanguage Language { private set; get; }

        /// <summary> 显示名 </summary>
        public string Name { private set; get; }

        /// <summary> 旗帜图标 </summary>
        public string Icon { private set; get; }

        /// <summary> 排序 </summary>
        public int Sort { private set; get; }

        /// <summary> 逗号分隔符 </summary>
        public string Separator { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 LanguageDef 实例(外部使用)
        /// </summary>
        /// <param name="language">语言</param>
        /// <param name="name">显示名</param>
        /// <param name="icon">旗帜图标</param>
        /// <param name="sort">排序</param>
        /// <param name="separator">逗号分隔符</param>
        public LanguageDef(ELanguage language, string name, string icon, int sort, string separator) 
        {
            Language = language;
            Name = name;
            Icon = icon;
            Sort = sort;
            Separator = separator;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 LanguageDef 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private LanguageDef(JSONNode node)
        {
            { if(!node["language"].IsNumber) { throw new SerializationException(); }  Language = (ELanguage)node["language"].AsInt; }
            { if(!node["name"].IsString) { throw new SerializationException(); }  Name = node["name"]; }
            { if(!node["icon"].IsString) { throw new SerializationException(); }  Icon = node["icon"]; }
            { if(!node["sort"].IsNumber) { throw new SerializationException(); }  Sort = node["sort"]; }
            { if(!node["separator"].IsString) { throw new SerializationException(); }  Separator = node["separator"]; }

            // Localization Key Begin
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 LanguageDef 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 LanguageDef</returns>
        public static LanguageDef DeserializeLanguageDef(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "language:"  + Language  + ","
                   + "name:"      + Name      + ","
                   + "icon:"      + Icon      + ","
                   + "sort:"      + Sort      + ","
                   + "separator:" + Separator + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}