//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// PropItem 数据类
    /// </summary>
    public sealed partial class PropItem : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = -929329866;

        /// <summary> 道具id </summary>
        public int Id { private set; get; }

        /// <summary> 道具数量 </summary>
        public int Count { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 PropItem 实例(外部使用)
        /// </summary>
        /// <param name="id">道具id</param>
        /// <param name="count">道具数量</param>
        public PropItem(int id, int count) 
        {
            Id = id;
            Count = count;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 PropItem 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private PropItem(JSONNode node)
        {
            { if(!node["Id"].IsNumber) { throw new SerializationException(); }  Id = node["Id"]; }
            { if(!node["Count"].IsNumber) { throw new SerializationException(); }  Count = node["Count"]; }

            // Localization Key Begin
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 PropItem 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 PropItem</returns>
        public static PropItem DeserializePropItem(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "Id:"    + Id    + ","
                   + "Count:" + Count + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}