//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// 属性
    /// </summary>
    public sealed partial class Property : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = -928497163;

        /// <summary> 物理攻击 </summary>
        public int PhysicalAttack { private set; get; }

        /// <summary> 魔法攻击 </summary>
        public int MagicAttack { private set; get; }

        /// <summary> 物理防御 </summary>
        public int PhysicalDefense { private set; get; }

        /// <summary> 魔法防御 </summary>
        public int MagicDefense { private set; get; }

        /// <summary> 生命值 </summary>
        public int Life { private set; get; }

        /// <summary> 暴击 </summary>
        public int Crit { private set; get; }

        /// <summary> 爆伤 </summary>
        public int BurstDamage { private set; get; }

        /// <summary> 精准 </summary>
        public int Precise { private set; get; }

        /// <summary> 格挡 </summary>
        public int Block { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 Property 实例(外部使用)
        /// </summary>
        /// <param name="PhysicalAttack">物理攻击</param>
        /// <param name="MagicAttack">魔法攻击</param>
        /// <param name="PhysicalDefense">物理防御</param>
        /// <param name="MagicDefense">魔法防御</param>
        /// <param name="Life">生命值</param>
        /// <param name="Crit">暴击</param>
        /// <param name="burstDamage">爆伤</param>
        /// <param name="precise">精准</param>
        /// <param name="block">格挡</param>
        public Property(int PhysicalAttack, int MagicAttack, int PhysicalDefense, int MagicDefense, int Life, int Crit, int burstDamage, int precise, int block) 
        {
            PhysicalAttack = PhysicalAttack;
            MagicAttack = MagicAttack;
            PhysicalDefense = PhysicalDefense;
            MagicDefense = MagicDefense;
            Life = Life;
            Crit = Crit;
            BurstDamage = burstDamage;
            Precise = precise;
            Block = block;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 Property 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private Property(JSONNode node)
        {
            { if(!node["PhysicalAttack"].IsNumber) { throw new SerializationException(); }  PhysicalAttack = node["PhysicalAttack"]; }
            { if(!node["MagicAttack"].IsNumber) { throw new SerializationException(); }  MagicAttack = node["MagicAttack"]; }
            { if(!node["PhysicalDefense"].IsNumber) { throw new SerializationException(); }  PhysicalDefense = node["PhysicalDefense"]; }
            { if(!node["MagicDefense"].IsNumber) { throw new SerializationException(); }  MagicDefense = node["MagicDefense"]; }
            { if(!node["Life"].IsNumber) { throw new SerializationException(); }  Life = node["Life"]; }
            { if(!node["Crit"].IsNumber) { throw new SerializationException(); }  Crit = node["Crit"]; }
            { if(!node["burstDamage"].IsNumber) { throw new SerializationException(); }  BurstDamage = node["burstDamage"]; }
            { if(!node["precise"].IsNumber) { throw new SerializationException(); }  Precise = node["precise"]; }
            { if(!node["block"].IsNumber) { throw new SerializationException(); }  Block = node["block"]; }

            // Localization Key Begin
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 Property 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 Property</returns>
        public static Property DeserializeProperty(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "PhysicalAttack:"  + PhysicalAttack  + ","
                   + "MagicAttack:"     + MagicAttack     + ","
                   + "PhysicalDefense:" + PhysicalDefense + ","
                   + "MagicDefense:"    + MagicDefense    + ","
                   + "Life:"            + Life            + ","
                   + "Crit:"            + Crit            + ","
                   + "burstDamage:"     + BurstDamage     + ","
                   + "precise:"         + Precise         + ","
                   + "block:"           + Block           + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}