
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Hotfix.Game.Tables
{
    public sealed partial class PropItem : BeanBase
    {
        public PropItem(int Id, int Count) 
        {
            this.Id = Id;
            this.Count = Count;
            PostInit();
        }

        public PropItem(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Count = _buf.ReadInt();
            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static PropItem DeserializePropItem(ByteBuf _buf)
        {
            return new PropItem(_buf);
        }

        /// <summary>
        /// 道具id
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 道具数量
        /// </summary>
        public int Count { private set; get; }
        public const int __ID__ = -929329866;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            PostResolveRef();
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Count:" + Count + ","
            + "}";
        }

        partial void PostInit();
        partial void PostResolveRef();
    }
}
