//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using SimpleJSON;
using Hotfix.Framework.Config;
using Cysharp.Threading.Tasks;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    public partial class TableManager
    {
        /// <summary> 本地化多语言表 </summary>
        private TbLocalization TbLocalization { set; get; }

        /// <summary> 成就表 </summary>
        private TbAchievement TbAchievement { set; get; }

        /// <summary> 道具表 </summary>
        private TbItem TbItem { set; get; }

        /// <summary> 实体组配置表 </summary>
        private TbEntityGroup TbEntityGroup { set; get; }

        /// <summary> 全局常量定义表 </summary>
        private TbGlobalDefine TbGlobalDefine { set; get; }

        /// <summary> 引导表 </summary>
        private TbGuide TbGuide { set; get; }

        /// <summary> 引导步骤表 </summary>
        private TbGuideStep TbGuideStep { set; get; }

        /// <summary> 红点表 </summary>
        private TbRedDot TbRedDot { set; get; }

        /// <summary> 声音表 </summary>
        private TbSound TbSound { set; get; }

        /// <summary> 声音组配置表 </summary>
        private TbSoundGroup TbSoundGroup { set; get; }

        /// <summary> UI配置表 </summary>
        private TbUIConfig TbUIConfig { set; get; }


        /// <summary> 是否加载完成 </summary>
        public bool IsLoaded { private set; get; }

        /// <summary> 框架配置模块 </summary>
        private ConfigModule m_ConfigModule;


        /// <summary>
        /// 初始化表管理器（关联配置模块并清空已有配置）
        /// </summary>
        /// <param name="configModule">配置管理模块</param>
        public void Init(ConfigModule configModule)
        {
            m_ConfigModule = configModule;
            m_ConfigModule.RemoveAllConfigs();
        }

        /// <summary>
        /// 异步加载全部配置表
        /// </summary>
        /// <param name="loader">取配置表 JSON 的加载委托</param>
        /// <returns>全部表加载完成</returns>
        /// <remarks>逐表建立、并行 await，全部完成后刷新引用</remarks>
        public async UniTask LoadAsync(Func<string, UniTask<JSONNode>> loader)
        {
            if (IsLoaded) return;

            IsLoaded = false;
            m_ConfigModule.RemoveAllConfigs();
            var loadTasks = new List<UniTask>();

            TbLocalization = new TbLocalization(() => loader("tblocalization"));
            loadTasks.Add(TbLocalization.LoadAsync());
            m_ConfigModule.AddConfig(nameof(TbLocalization), TbLocalization);

            TbAchievement = new TbAchievement(() => loader("tbachievement"));
            loadTasks.Add(TbAchievement.LoadAsync());
            m_ConfigModule.AddConfig(nameof(TbAchievement), TbAchievement);

            TbItem = new TbItem(() => loader("tbitem"));
            loadTasks.Add(TbItem.LoadAsync());
            m_ConfigModule.AddConfig(nameof(TbItem), TbItem);

            TbEntityGroup = new TbEntityGroup(() => loader("tbentitygroup"));
            loadTasks.Add(TbEntityGroup.LoadAsync());
            m_ConfigModule.AddConfig(nameof(TbEntityGroup), TbEntityGroup);

            TbGlobalDefine = new TbGlobalDefine(() => loader("tbglobaldefine"));
            loadTasks.Add(TbGlobalDefine.LoadAsync());
            m_ConfigModule.AddConfig(nameof(TbGlobalDefine), TbGlobalDefine);

            TbGuide = new TbGuide(() => loader("tbguide"));
            loadTasks.Add(TbGuide.LoadAsync());
            m_ConfigModule.AddConfig(nameof(TbGuide), TbGuide);

            TbGuideStep = new TbGuideStep(() => loader("tbguidestep"));
            loadTasks.Add(TbGuideStep.LoadAsync());
            m_ConfigModule.AddConfig(nameof(TbGuideStep), TbGuideStep);

            TbRedDot = new TbRedDot(() => loader("tbreddot"));
            loadTasks.Add(TbRedDot.LoadAsync());
            m_ConfigModule.AddConfig(nameof(TbRedDot), TbRedDot);

            TbSound = new TbSound(() => loader("tbsound"));
            loadTasks.Add(TbSound.LoadAsync());
            m_ConfigModule.AddConfig(nameof(TbSound), TbSound);

            TbSoundGroup = new TbSoundGroup(() => loader("tbsoundgroup"));
            loadTasks.Add(TbSoundGroup.LoadAsync());
            m_ConfigModule.AddConfig(nameof(TbSoundGroup), TbSoundGroup);

            TbUIConfig = new TbUIConfig(() => loader("tbuiconfig"));
            loadTasks.Add(TbUIConfig.LoadAsync());
            m_ConfigModule.AddConfig(nameof(TbUIConfig), TbUIConfig);

            await UniTask.WhenAll(loadTasks);

            OnInit();
            ResolveRef();

            IsLoaded = true;
        }

        /// <summary>
        /// 解析所有配置表的跨表引用（表之间已加载完毕）
        /// </summary>
        private void ResolveRef()
        {
            TbLocalization.ResolveRef(this);
            TbAchievement.ResolveRef(this);
            TbItem.ResolveRef(this);
            TbEntityGroup.ResolveRef(this);
            TbGlobalDefine.ResolveRef(this);
            TbGuide.ResolveRef(this);
            TbGuideStep.ResolveRef(this);
            TbRedDot.ResolveRef(this);
            TbSound.ResolveRef(this);
            TbSoundGroup.ResolveRef(this);
            TbUIConfig.ResolveRef(this);
        }

        /// <summary>
        /// 为所有配置表设置本地化翻译器
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        /// <exception cref="InvalidOperationException">如果未加载完成将抛出此异常</exception>
        public void SetTranslateText(Func<string, string, string> translator)
        {
            if (IsLoaded == false) throw new InvalidOperationException("为配置表设置本地化翻译器失败，配置表没有被加载!");

            TbLocalization.TranslateText(translator);
            TbAchievement.TranslateText(translator);
            TbItem.TranslateText(translator);
            TbEntityGroup.TranslateText(translator);
            TbGlobalDefine.TranslateText(translator);
            TbGuide.TranslateText(translator);
            TbGuideStep.TranslateText(translator);
            TbRedDot.TranslateText(translator);
            TbSound.TranslateText(translator);
            TbSoundGroup.TranslateText(translator);
            TbUIConfig.TranslateText(translator);
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成一些所有配置表加载完成后的自定义预处理收尾工作
        /// </summary>
        partial void OnInit();
    }
}