//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// vec2 数据类
    /// </summary>
    public partial struct vec2
    {

        public float X { private set; get; }

        public float Y { private set; get; }


        /// <summary>
        /// 创建 vec2 实例(外部使用)
        /// </summary>
        /// <param name="x"></param>
        /// <param name="y"></param>
        public vec2(float x, float y) 
        {
            X = x;
            Y = y;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 vec2 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private vec2(JSONNode node)
        {
            { if(!node["x"].IsNumber) { throw new SerializationException(); }  X = node["x"]; }
            { if(!node["y"].IsNumber) { throw new SerializationException(); }  Y = node["y"]; }

            // Localization Key Begin
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 vec2 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 vec2</returns>
        public static vec2 Deserializevec2(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "x:" + X + ","
                   + "y:" + Y + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}