
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Hotfix.Game.Tables
{
    public partial struct vec3
    {
        public vec3(float X, float Y, float Z) 
        {
            this.X = X;
            this.Y = Y;
            this.Z = Z;
            PostInit();
        }

        public vec3(ByteBuf _buf) 
        {
            X = _buf.ReadFloat();
            Y = _buf.ReadFloat();
            Z = _buf.ReadFloat();
            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static vec3 Deserializevec3(ByteBuf _buf)
        {
            return new vec3(_buf);
        }

        public float X { private set; get; }
        public float Y { private set; get; }
        public float Z { private set; get; }

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            PostResolveRef();
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "x:" + X + ","
            + "y:" + Y + ","
            + "z:" + Z + ","
            + "}";
        }

        partial void PostInit();
        partial void PostResolveRef();
    }
}
