
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Hotfix.Game.Tables.Tables
{
    public sealed partial class Achievement : BeanBase
    {
        public Achievement(int Id, string Icon, string Name, string Desc, System.Collections.Generic.List<int> UnlockCondition) 
        {
            this.Id = Id;
            this.Icon = Icon;
            this.Name = Name;
            this.Desc = Desc;
            this.UnlockCondition = UnlockCondition;
            PostInit();
        }

        public Achievement(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Icon = _buf.ReadString();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            {int n0 = _buf.ReadSize(); UnlockCondition = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); UnlockCondition.Add(_e0);}}
            // Localization Key Begin
            Name_Localization_Key = Name;
            Desc_Localization_Key = Desc;
            // Localization Key End
            PostInit();
        }

        public static Achievement DeserializeAchievement(ByteBuf _buf)
        {
            return new Tables.Achievement(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 图标
        /// </summary>
        public string Icon { private set; get; }
        /// <summary>
        /// 成就名称
        /// </summary>
        public string Name { private set; get; }
        /// <summary>
        /// 成就名称 的多语言Key
        /// </summary>
        public readonly string Name_Localization_Key;
        /// <summary>
        /// 描述信息
        /// </summary>
        public string Desc { private set; get; }
        /// <summary>
        /// 描述信息 的多语言Key
        /// </summary>
        public readonly string Desc_Localization_Key;
        /// <summary>
        /// 成就解锁条件
        /// </summary>
        public System.Collections.Generic.List<int> UnlockCondition { private set; get; }
        public const int __ID__ = -1048610522;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            
            
            PostResolveRef();
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
            Name = translator(Name_Localization_Key, Name);
            Desc = translator(Desc_Localization_Key, Desc);
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "icon:" + Icon + ","
            + "name:" + Name + ","
            + "desc:" + Desc + ","
            + "unlockCondition:" + Luban.StringUtil.CollectionToString(UnlockCondition) + ","
            + "}";
        }

        partial void PostInit();
        partial void PostResolveRef();
    }
}
