//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// Achievement 数据类
    /// </summary>
    public sealed partial class Achievement : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = -1048610522;

        /// <summary> ID </summary>
        public int Id { private set; get; }

        /// <summary> 图标 </summary>
        public string Icon { private set; get; }

        /// <summary> 成就名称 </summary>
        public string Name { private set; get; }
        /// <summary> 成就名称 的多语言Key </summary>
        private readonly string Name_Localization_Key;

        /// <summary> 描述信息 </summary>
        public string Desc { private set; get; }
        /// <summary> 描述信息 的多语言Key </summary>
        private readonly string Desc_Localization_Key;

        /// <summary> 成就解锁条件 </summary>
        public System.Collections.Generic.List<int> UnlockCondition { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 Achievement 实例(外部使用)
        /// </summary>
        /// <param name="id">ID</param>
        /// <param name="icon">图标</param>
        /// <param name="name">成就名称</param>
        /// <param name="desc">描述信息</param>
        /// <param name="unlockCondition">成就解锁条件</param>
        public Achievement(int id, string icon, string name, string desc, System.Collections.Generic.List<int> unlockCondition) 
        {
            Id = id;
            Icon = icon;
            Name = name;
            Desc = desc;
            UnlockCondition = unlockCondition;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 Achievement 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private Achievement(JSONNode node)
        {
            { if(!node["id"].IsNumber) { throw new SerializationException(); }  Id = node["id"]; }
            { if(!node["icon"].IsString) { throw new SerializationException(); }  Icon = node["icon"]; }
            { if(!node["name"].IsString) { throw new SerializationException(); }  Name = node["name"]; }
            { if(!node["desc"].IsString) { throw new SerializationException(); }  Desc = node["desc"]; }
            { var __json0 = node["unlock_condition"]; if(!__json0.IsArray) { throw new SerializationException(); } UnlockCondition = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  UnlockCondition.Add(__v0); }   }

            // Localization Key Begin
            Name_Localization_Key = Name;
            Desc_Localization_Key = Desc;
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 Achievement 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 Achievement</returns>
        public static Achievement DeserializeAchievement(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
            Name = translator(Name_Localization_Key, Name);
            Desc = translator(Desc_Localization_Key, Desc);
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "id:"              + Id              + ","
                   + "icon:"            + Icon            + ","
                   + "name:"            + Name            + ","
                   + "desc:"            + Desc            + ","
                   + "unlockCondition:" + Luban.StringUtil.CollectionToString(UnlockCondition) + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}