
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Hotfix.Game.Tables
{
    public sealed partial class EntityGroup : BeanBase
    {
        public EntityGroup(EEntityGroup Id, float InstanceAutoReleaseInterval, int InstanceCapacity, float InstanceExpireTime, int InstancePriority) 
        {
            this.Id = Id;
            this.InstanceAutoReleaseInterval = InstanceAutoReleaseInterval;
            this.InstanceCapacity = InstanceCapacity;
            this.InstanceExpireTime = InstanceExpireTime;
            this.InstancePriority = InstancePriority;
            PostInit();
        }

        public EntityGroup(JSONNode _buf)
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = (EEntityGroup)_buf["Id"].AsInt; }
            { if(!_buf["InstanceAutoReleaseInterval"].IsNumber) { throw new SerializationException(); }  InstanceAutoReleaseInterval = _buf["InstanceAutoReleaseInterval"]; }
            { if(!_buf["InstanceCapacity"].IsNumber) { throw new SerializationException(); }  InstanceCapacity = _buf["InstanceCapacity"]; }
            { if(!_buf["InstanceExpireTime"].IsNumber) { throw new SerializationException(); }  InstanceExpireTime = _buf["InstanceExpireTime"]; }
            { if(!_buf["InstancePriority"].IsNumber) { throw new SerializationException(); }  InstancePriority = _buf["InstancePriority"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static EntityGroup DeserializeEntityGroup(JSONNode _buf)
        {
            return new EntityGroup(_buf);
        }

        /// <summary>
        /// 实体组ID
        /// </summary>
        public EEntityGroup Id { private set; get; }
        /// <summary>
        /// 自动释放间隔(秒)
        /// </summary>
        public float InstanceAutoReleaseInterval { private set; get; }
        /// <summary>
        /// 对象池容量
        /// </summary>
        public int InstanceCapacity { private set; get; }
        /// <summary>
        /// 对象过期时间(秒)
        /// </summary>
        public float InstanceExpireTime { private set; get; }
        /// <summary>
        /// 对象池优先级
        /// </summary>
        public int InstancePriority { private set; get; }
        public const int __ID__ = -1536753069;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "InstanceAutoReleaseInterval:" + InstanceAutoReleaseInterval + ","
            + "InstanceCapacity:" + InstanceCapacity + ","
            + "InstanceExpireTime:" + InstanceExpireTime + ","
            + "InstancePriority:" + InstancePriority + ","
            + "}";
        }

        partial void PostInit();
    }
}
