//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// EntityGroup 数据类
    /// </summary>
    public sealed partial class EntityGroup : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = -1536753069;

        /// <summary> 实体组ID </summary>
        public EEntityGroup Id { private set; get; }

        /// <summary> 实体对象池自动销毁检查间隔(秒) </summary>
        public float PoolAutoDisposeCheckInterval { private set; get; }

        /// <summary> 实体对象池容量 </summary>
        public int PoolCapacity { private set; get; }

        /// <summary> 实体对象闲置后过期秒数 </summary>
        public float PoolExpireTimeAfterIdle { private set; get; }

        /// <summary> 实体对象池优先级 </summary>
        public int PoolPriority { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 EntityGroup 实例(外部使用)
        /// </summary>
        /// <param name="Id">实体组ID</param>
        /// <param name="PoolAutoDisposeCheckInterval">实体对象池自动销毁检查间隔(秒)</param>
        /// <param name="PoolCapacity">实体对象池容量</param>
        /// <param name="PoolExpireTimeAfterIdle">实体对象闲置后过期秒数</param>
        /// <param name="PoolPriority">实体对象池优先级</param>
        public EntityGroup(EEntityGroup Id, float PoolAutoDisposeCheckInterval, int PoolCapacity, float PoolExpireTimeAfterIdle, int PoolPriority) 
        {
            Id = Id;
            PoolAutoDisposeCheckInterval = PoolAutoDisposeCheckInterval;
            PoolCapacity = PoolCapacity;
            PoolExpireTimeAfterIdle = PoolExpireTimeAfterIdle;
            PoolPriority = PoolPriority;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 EntityGroup 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private EntityGroup(JSONNode node)
        {
            { if(!node["Id"].IsNumber) { throw new SerializationException(); }  Id = (EEntityGroup)node["Id"].AsInt; }
            { if(!node["PoolAutoDisposeCheckInterval"].IsNumber) { throw new SerializationException(); }  PoolAutoDisposeCheckInterval = node["PoolAutoDisposeCheckInterval"]; }
            { if(!node["PoolCapacity"].IsNumber) { throw new SerializationException(); }  PoolCapacity = node["PoolCapacity"]; }
            { if(!node["PoolExpireTimeAfterIdle"].IsNumber) { throw new SerializationException(); }  PoolExpireTimeAfterIdle = node["PoolExpireTimeAfterIdle"]; }
            { if(!node["PoolPriority"].IsNumber) { throw new SerializationException(); }  PoolPriority = node["PoolPriority"]; }

            // Localization Key Begin
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 EntityGroup 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 EntityGroup</returns>
        public static EntityGroup DeserializeEntityGroup(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "Id:"                           + Id                           + ","
                   + "PoolAutoDisposeCheckInterval:" + PoolAutoDisposeCheckInterval + ","
                   + "PoolCapacity:"                 + PoolCapacity                 + ","
                   + "PoolExpireTimeAfterIdle:"      + PoolExpireTimeAfterIdle      + ","
                   + "PoolPriority:"                 + PoolPriority                 + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}