
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Hotfix.Game.Config.Tables
{
    public sealed partial class EntityGroup : BeanBase
    {
        public EntityGroup(EEntityGroup Id, float PoolAutoDisposeCheckInterval, int PoolCapacity, float PoolExpireTimeAfterIdle, int PoolPriority) 
        {
            this.Id = Id;
            this.PoolAutoDisposeCheckInterval = PoolAutoDisposeCheckInterval;
            this.PoolCapacity = PoolCapacity;
            this.PoolExpireTimeAfterIdle = PoolExpireTimeAfterIdle;
            this.PoolPriority = PoolPriority;
            PostInit();
        }

        public EntityGroup(JSONNode _buf)
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = (EEntityGroup)_buf["Id"].AsInt; }
            { if(!_buf["PoolAutoDisposeCheckInterval"].IsNumber) { throw new SerializationException(); }  PoolAutoDisposeCheckInterval = _buf["PoolAutoDisposeCheckInterval"]; }
            { if(!_buf["PoolCapacity"].IsNumber) { throw new SerializationException(); }  PoolCapacity = _buf["PoolCapacity"]; }
            { if(!_buf["PoolExpireTimeAfterIdle"].IsNumber) { throw new SerializationException(); }  PoolExpireTimeAfterIdle = _buf["PoolExpireTimeAfterIdle"]; }
            { if(!_buf["PoolPriority"].IsNumber) { throw new SerializationException(); }  PoolPriority = _buf["PoolPriority"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static EntityGroup DeserializeEntityGroup(JSONNode _buf)
        {
            return new Tables.EntityGroup(_buf);
        }

        /// <summary>
        /// 实体组ID
        /// </summary>
        public EEntityGroup Id { private set; get; }
        /// <summary>
        /// 实体对象池自动销毁检查间隔(秒)
        /// </summary>
        public float PoolAutoDisposeCheckInterval { private set; get; }
        /// <summary>
        /// 实体对象池容量
        /// </summary>
        public int PoolCapacity { private set; get; }
        /// <summary>
        /// 实体对象闲置后过期秒数
        /// </summary>
        public float PoolExpireTimeAfterIdle { private set; get; }
        /// <summary>
        /// 实体对象池优先级
        /// </summary>
        public int PoolPriority { private set; get; }
        public const int __ID__ = -1536753069;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "PoolAutoDisposeCheckInterval:" + PoolAutoDisposeCheckInterval + ","
            + "PoolCapacity:" + PoolCapacity + ","
            + "PoolExpireTimeAfterIdle:" + PoolExpireTimeAfterIdle + ","
            + "PoolPriority:" + PoolPriority + ","
            + "}";
        }

        partial void PostInit();
    }
}
