
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Hotfix.Game.Tables.Tables
{
    public sealed partial class GlobalDefine : BeanBase
    {
        public GlobalDefine(long PlayerInitialCoin, int PlayerInitialHp) 
        {
            this.PlayerInitialCoin = PlayerInitialCoin;
            this.PlayerInitialHp = PlayerInitialHp;
            PostInit();
        }

        public GlobalDefine(ByteBuf _buf) 
        {
            PlayerInitialCoin = _buf.ReadLong();
            PlayerInitialHp = _buf.ReadInt();
            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static GlobalDefine DeserializeGlobalDefine(ByteBuf _buf)
        {
            return new Tables.GlobalDefine(_buf);
        }

        /// <summary>
        /// 玩家初始金币
        /// </summary>
        public long PlayerInitialCoin { private set; get; }
        /// <summary>
        /// 玩家初始血量
        /// </summary>
        public int PlayerInitialHp { private set; get; }
        public const int __ID__ = -1887201241;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            PostResolveRef();
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "playerInitialCoin:" + PlayerInitialCoin + ","
            + "playerInitialHp:" + PlayerInitialHp + ","
            + "}";
        }

        partial void PostInit();
        partial void PostResolveRef();
    }
}
