//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// GlobalDefine 数据类
    /// </summary>
    public sealed partial class GlobalDefine : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = -1887201241;

        /// <summary> 玩家初始金币 </summary>
        public long PlayerInitialCoin { private set; get; }

        /// <summary> 玩家初始血量 </summary>
        public int PlayerInitialHp { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 GlobalDefine 实例(外部使用)
        /// </summary>
        /// <param name="playerInitialCoin">玩家初始金币</param>
        /// <param name="playerInitialHp">玩家初始血量</param>
        public GlobalDefine(long playerInitialCoin, int playerInitialHp) 
        {
            PlayerInitialCoin = playerInitialCoin;
            PlayerInitialHp = playerInitialHp;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 GlobalDefine 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private GlobalDefine(JSONNode node)
        {
            { if(!node["player_initial_coin"].IsNumber) { throw new SerializationException(); }  PlayerInitialCoin = node["player_initial_coin"]; }
            { if(!node["player_initial_hp"].IsNumber) { throw new SerializationException(); }  PlayerInitialHp = node["player_initial_hp"]; }

            // Localization Key Begin
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 GlobalDefine 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 GlobalDefine</returns>
        public static GlobalDefine DeserializeGlobalDefine(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "playerInitialCoin:" + PlayerInitialCoin + ","
                   + "playerInitialHp:"   + PlayerInitialHp   + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}