
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Hotfix.Game.Config.Tables
{
    public sealed partial class GlobalDefine : BeanBase
    {
        public GlobalDefine(long PlayerInitialCoin, int PlayerInitialHp) 
        {
            this.PlayerInitialCoin = PlayerInitialCoin;
            this.PlayerInitialHp = PlayerInitialHp;
            PostInit();
        }

        public GlobalDefine(JSONNode _buf)
        {
            { if(!_buf["player_initial_coin"].IsNumber) { throw new SerializationException(); }  PlayerInitialCoin = _buf["player_initial_coin"]; }
            { if(!_buf["player_initial_hp"].IsNumber) { throw new SerializationException(); }  PlayerInitialHp = _buf["player_initial_hp"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static GlobalDefine DeserializeGlobalDefine(JSONNode _buf)
        {
            return new Tables.GlobalDefine(_buf);
        }

        /// <summary>
        /// 玩家初始金币
        /// </summary>
        public long PlayerInitialCoin { private set; get; }
        /// <summary>
        /// 玩家初始血量
        /// </summary>
        public int PlayerInitialHp { private set; get; }
        public const int __ID__ = -1887201241;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "playerInitialCoin:" + PlayerInitialCoin + ","
            + "playerInitialHp:" + PlayerInitialHp + ","
            + "}";
        }

        partial void PostInit();
    }
}
