//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// Guide 数据类
    /// </summary>
    public sealed partial class Guide : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = 332376627;

        /// <summary> 引导ID </summary>
        public int Id { private set; get; }

        /// <summary> 引导名称 </summary>
        public string Name { private set; get; }

        /// <summary> 起始步骤ID </summary>
        public int StartStepId { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 Guide 实例(外部使用)
        /// </summary>
        /// <param name="id">引导ID</param>
        /// <param name="name">引导名称</param>
        /// <param name="startStepId">起始步骤ID</param>
        public Guide(int id, string name, int startStepId) 
        {
            Id = id;
            Name = name;
            StartStepId = startStepId;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 Guide 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private Guide(JSONNode node)
        {
            { if(!node["Id"].IsNumber) { throw new SerializationException(); }  Id = node["Id"]; }
            { if(!node["Name"].IsString) { throw new SerializationException(); }  Name = node["Name"]; }
            { if(!node["StartStepId"].IsNumber) { throw new SerializationException(); }  StartStepId = node["StartStepId"]; }

            // Localization Key Begin
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 Guide 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 Guide</returns>
        public static Guide DeserializeGuide(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "Id:"          + Id          + ","
                   + "Name:"        + Name        + ","
                   + "StartStepId:" + StartStepId + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}