//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// GuideStep 数据类
    /// </summary>
    public sealed partial class GuideStep : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = -220146785;

        /// <summary> 步骤ID </summary>
        public int Id { private set; get; }

        /// <summary> 所属引导ID </summary>
        public int GuideId { private set; get; }

        /// <summary> 步骤类型 </summary>
        public EStepType StepType { private set; get; }

        /// <summary> 下一步骤ID(空=结束) </summary>
        public int? NextStepId { private set; get; }

        /// <summary> 是否可跳过 </summary>
        public bool CanJump { private set; get; }

        /// <summary> 目标窗口 </summary>
        public string TargetWindow { private set; get; }

        /// <summary> 目标UI </summary>
        public string TargetUI { private set; get; }

        /// <summary> 对话内容 </summary>
        public string DialogContent { private set; get; }

        /// <summary> 等待时间(秒) </summary>
        public float WaitTime { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 GuideStep 实例(外部使用)
        /// </summary>
        /// <param name="Id">步骤ID</param>
        /// <param name="GuideId">所属引导ID</param>
        /// <param name="StepType">步骤类型</param>
        /// <param name="NextStepId">下一步骤ID(空=结束)</param>
        /// <param name="CanJump">是否可跳过</param>
        /// <param name="TargetWindow">目标窗口</param>
        /// <param name="TargetUI">目标UI</param>
        /// <param name="DialogContent">对话内容</param>
        /// <param name="WaitTime">等待时间(秒)</param>
        public GuideStep(int Id, int GuideId, EStepType StepType, int? NextStepId, bool CanJump, string TargetWindow, string TargetUI, string DialogContent, float WaitTime) 
        {
            Id = Id;
            GuideId = GuideId;
            StepType = StepType;
            NextStepId = NextStepId;
            CanJump = CanJump;
            TargetWindow = TargetWindow;
            TargetUI = TargetUI;
            DialogContent = DialogContent;
            WaitTime = WaitTime;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 GuideStep 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private GuideStep(JSONNode node)
        {
            { if(!node["Id"].IsNumber) { throw new SerializationException(); }  Id = node["Id"]; }
            { if(!node["GuideId"].IsNumber) { throw new SerializationException(); }  GuideId = node["GuideId"]; }
            { if(!node["StepType"].IsNumber) { throw new SerializationException(); }  StepType = (EStepType)node["StepType"].AsInt; }
            { var _j = node["NextStepId"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  NextStepId = _j; } } else { NextStepId = null; } }
            { if(!node["CanJump"].IsBoolean) { throw new SerializationException(); }  CanJump = node["CanJump"]; }
            { if(!node["TargetWindow"].IsString) { throw new SerializationException(); }  TargetWindow = node["TargetWindow"]; }
            { if(!node["TargetUI"].IsString) { throw new SerializationException(); }  TargetUI = node["TargetUI"]; }
            { if(!node["DialogContent"].IsString) { throw new SerializationException(); }  DialogContent = node["DialogContent"]; }
            { if(!node["WaitTime"].IsNumber) { throw new SerializationException(); }  WaitTime = node["WaitTime"]; }

            // Localization Key Begin
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 GuideStep 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 GuideStep</returns>
        public static GuideStep DeserializeGuideStep(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "Id:"            + Id            + ","
                   + "GuideId:"       + GuideId       + ","
                   + "StepType:"      + StepType      + ","
                   + "NextStepId:"    + NextStepId    + ","
                   + "CanJump:"       + CanJump       + ","
                   + "TargetWindow:"  + TargetWindow  + ","
                   + "TargetUI:"      + TargetUI      + ","
                   + "DialogContent:" + DialogContent + ","
                   + "WaitTime:"      + WaitTime      + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}