
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Hotfix.Game.Config.Tables
{
    public sealed partial class Guide : BeanBase
    {
        public Guide(int Id, string Name, int StartStepId) 
        {
            this.Id = Id;
            this.Name = Name;
            this.StartStepId = StartStepId;
            PostInit();
        }

        public Guide(JSONNode _buf)
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["StartStepId"].IsNumber) { throw new SerializationException(); }  StartStepId = _buf["StartStepId"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static Guide DeserializeGuide(JSONNode _buf)
        {
            return new Tables.Guide(_buf);
        }

        /// <summary>
        /// 引导ID
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 引导名称
        /// </summary>
        public string Name { private set; get; }
        /// <summary>
        /// 起始步骤ID
        /// </summary>
        public int StartStepId { private set; get; }
        public const int __ID__ = 332376627;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Name:" + Name + ","
            + "StartStepId:" + StartStepId + ","
            + "}";
        }

        partial void PostInit();
    }
}
