
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Hotfix.Game.Tables.Tables
{
    public sealed partial class GuideStep : BeanBase
    {
        public GuideStep(int Id, int GuideId, EStepType StepType, int? NextStepId, bool CanJump, string TargetWindow, string TargetUI, string DialogContent, float WaitTime) 
        {
            this.Id = Id;
            this.GuideId = GuideId;
            this.StepType = StepType;
            this.NextStepId = NextStepId;
            this.CanJump = CanJump;
            this.TargetWindow = TargetWindow;
            this.TargetUI = TargetUI;
            this.DialogContent = DialogContent;
            this.WaitTime = WaitTime;
            PostInit();
        }

        public GuideStep(JSONNode _buf)
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = _buf["Id"]; }
            { if(!_buf["GuideId"].IsNumber) { throw new SerializationException(); }  GuideId = _buf["GuideId"]; }
            { if(!_buf["StepType"].IsNumber) { throw new SerializationException(); }  StepType = (EStepType)_buf["StepType"].AsInt; }
            { var _j = _buf["NextStepId"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  NextStepId = _j; } } else { NextStepId = null; } }
            { if(!_buf["CanJump"].IsBoolean) { throw new SerializationException(); }  CanJump = _buf["CanJump"]; }
            { if(!_buf["TargetWindow"].IsString) { throw new SerializationException(); }  TargetWindow = _buf["TargetWindow"]; }
            { if(!_buf["TargetUI"].IsString) { throw new SerializationException(); }  TargetUI = _buf["TargetUI"]; }
            { if(!_buf["DialogContent"].IsString) { throw new SerializationException(); }  DialogContent = _buf["DialogContent"]; }
            { if(!_buf["WaitTime"].IsNumber) { throw new SerializationException(); }  WaitTime = _buf["WaitTime"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static GuideStep DeserializeGuideStep(JSONNode _buf)
        {
            return new Tables.GuideStep(_buf);
        }

        /// <summary>
        /// 步骤ID
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 所属引导ID
        /// </summary>
        public int GuideId { private set; get; }
        /// <summary>
        /// 步骤类型
        /// </summary>
        public EStepType StepType { private set; get; }
        /// <summary>
        /// 下一步骤ID(空=结束)
        /// </summary>
        public int? NextStepId { private set; get; }
        /// <summary>
        /// 是否可跳过
        /// </summary>
        public bool CanJump { private set; get; }
        /// <summary>
        /// 目标窗口
        /// </summary>
        public string TargetWindow { private set; get; }
        /// <summary>
        /// 目标UI
        /// </summary>
        public string TargetUI { private set; get; }
        /// <summary>
        /// 对话内容
        /// </summary>
        public string DialogContent { private set; get; }
        /// <summary>
        /// 等待时间(秒)
        /// </summary>
        public float WaitTime { private set; get; }
        public const int __ID__ = -220146785;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "GuideId:" + GuideId + ","
            + "StepType:" + StepType + ","
            + "NextStepId:" + NextStepId + ","
            + "CanJump:" + CanJump + ","
            + "TargetWindow:" + TargetWindow + ","
            + "TargetUI:" + TargetUI + ","
            + "DialogContent:" + DialogContent + ","
            + "WaitTime:" + WaitTime + ","
            + "}";
        }

        partial void PostInit();
    }
}
