//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// Item 数据类
    /// </summary>
    public sealed partial class Item : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = -1513240324;

        /// <summary> ID </summary>
        public int Id { private set; get; }

        /// <summary> 名称 </summary>
        public string Name { private set; get; }
        /// <summary> 名称 的多语言Key </summary>
        private readonly string Name_Localization_Key;

        /// <summary> 描述 </summary>
        public string Desc { private set; get; }
        /// <summary> 描述 的多语言Key </summary>
        private readonly string Desc_Localization_Key;

        /// <summary> 图标 </summary>
        public string Icon { private set; get; }

        /// <summary> 背景图 </summary>
        public string Bg { private set; get; }

        /// <summary> 品质 </summary>
        public EQuality Quality { private set; get; }

        /// <summary> 类型 </summary>
        public EItemType Type { private set; get; }

        /// <summary> 子类型 </summary>
        public EItemSubType SubType { private set; get; }

        /// <summary> 能否使用 </summary>
        public EItemUseType CanUse { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 Item 实例(外部使用)
        /// </summary>
        /// <param name="id">ID</param>
        /// <param name="name">名称</param>
        /// <param name="desc">描述</param>
        /// <param name="icon">图标</param>
        /// <param name="bg">背景图</param>
        /// <param name="quality">品质</param>
        /// <param name="type">类型</param>
        /// <param name="subType">子类型</param>
        /// <param name="canUse">能否使用</param>
        public Item(int id, string name, string desc, string icon, string bg, EQuality quality, EItemType type, EItemSubType subType, EItemUseType canUse) 
        {
            Id = id;
            Name = name;
            Desc = desc;
            Icon = icon;
            Bg = bg;
            Quality = quality;
            Type = type;
            SubType = subType;
            CanUse = canUse;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 Item 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private Item(JSONNode node)
        {
            { if(!node["id"].IsNumber) { throw new SerializationException(); }  Id = node["id"]; }
            { if(!node["name"].IsString) { throw new SerializationException(); }  Name = node["name"]; }
            { if(!node["desc"].IsString) { throw new SerializationException(); }  Desc = node["desc"]; }
            { if(!node["icon"].IsString) { throw new SerializationException(); }  Icon = node["icon"]; }
            { if(!node["bg"].IsString) { throw new SerializationException(); }  Bg = node["bg"]; }
            { if(!node["quality"].IsNumber) { throw new SerializationException(); }  Quality = (EQuality)node["quality"].AsInt; }
            { if(!node["type"].IsNumber) { throw new SerializationException(); }  Type = (EItemType)node["type"].AsInt; }
            { if(!node["sub_type"].IsNumber) { throw new SerializationException(); }  SubType = (EItemSubType)node["sub_type"].AsInt; }
            { if(!node["can_use"].IsNumber) { throw new SerializationException(); }  CanUse = (EItemUseType)node["can_use"].AsInt; }

            // Localization Key Begin
            Name_Localization_Key = Name;
            Desc_Localization_Key = Desc;
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 Item 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 Item</returns>
        public static Item DeserializeItem(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
            Name = translator(Name_Localization_Key, Name);
            Desc = translator(Desc_Localization_Key, Desc);
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "id:"      + Id      + ","
                   + "name:"    + Name    + ","
                   + "desc:"    + Desc    + ","
                   + "icon:"    + Icon    + ","
                   + "bg:"      + Bg      + ","
                   + "quality:" + Quality + ","
                   + "type:"    + Type    + ","
                   + "subType:" + SubType + ","
                   + "canUse:"  + CanUse  + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}