
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Hotfix.Game.Tables.Tables
{
    public sealed partial class Item : BeanBase
    {
        public Item(int Id, string Name, string Desc, string Icon, string Bg, EQuality Quality, ItemType Type, ItemSubType SubType, ItemUseType CanUse) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Desc = Desc;
            this.Icon = Icon;
            this.Bg = Bg;
            this.Quality = Quality;
            this.Type = Type;
            this.SubType = SubType;
            this.CanUse = CanUse;
            PostInit();
        }

        public Item(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            Name = _buf.ReadString();
            Desc = _buf.ReadString();
            Icon = _buf.ReadString();
            Bg = _buf.ReadString();
            Quality = (EQuality)_buf.ReadInt();
            Type = (ItemType)_buf.ReadInt();
            SubType = (ItemSubType)_buf.ReadInt();
            CanUse = (ItemUseType)_buf.ReadInt();
            // Localization Key Begin
            Name_Localization_Key = Name;
            Desc_Localization_Key = Desc;
            // Localization Key End
            PostInit();
        }

        public static Item DeserializeItem(ByteBuf _buf)
        {
            return new Tables.Item(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 名称
        /// </summary>
        public string Name { private set; get; }
        /// <summary>
        /// 名称 的多语言Key
        /// </summary>
        public readonly string Name_Localization_Key;
        /// <summary>
        /// 描述
        /// </summary>
        public string Desc { private set; get; }
        /// <summary>
        /// 描述 的多语言Key
        /// </summary>
        public readonly string Desc_Localization_Key;
        /// <summary>
        /// 图标
        /// </summary>
        public string Icon { private set; get; }
        /// <summary>
        /// 背景图
        /// </summary>
        public string Bg { private set; get; }
        /// <summary>
        /// 品质
        /// </summary>
        public EQuality Quality { private set; get; }
        /// <summary>
        /// 类型
        /// </summary>
        public ItemType Type { private set; get; }
        /// <summary>
        /// 子类型
        /// </summary>
        public ItemSubType SubType { private set; get; }
        /// <summary>
        /// 能否使用
        /// </summary>
        public ItemUseType CanUse { private set; get; }
        public const int __ID__ = -1513240324;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            
            
            
            
            
            
            PostResolveRef();
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
            Name = translator(Name_Localization_Key, Name);
            Desc = translator(Desc_Localization_Key, Desc);
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "name:" + Name + ","
            + "desc:" + Desc + ","
            + "icon:" + Icon + ","
            + "bg:" + Bg + ","
            + "quality:" + Quality + ","
            + "type:" + Type + ","
            + "subType:" + SubType + ","
            + "canUse:" + CanUse + ","
            + "}";
        }

        partial void PostInit();
        partial void PostResolveRef();
    }
}
