
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Hotfix.Game.Tables.Tables
{
    public sealed partial class RedDot : BeanBase
    {
        public RedDot(ERedDotKey Id, ERedDotKey? ParentId, ERedDotDisplayMode DisplayMode, ERedDotCleanStrategy CleanStrategy) 
        {
            this.Id = Id;
            this.ParentId = ParentId;
            this.DisplayMode = DisplayMode;
            this.CleanStrategy = CleanStrategy;
            PostInit();
        }

        public RedDot(ByteBuf _buf) 
        {
            Id = (ERedDotKey)_buf.ReadInt();
            if(_buf.ReadBool()){ ParentId = (ERedDotKey)_buf.ReadInt(); } else { ParentId = null; }
            DisplayMode = (ERedDotDisplayMode)_buf.ReadInt();
            CleanStrategy = (ERedDotCleanStrategy)_buf.ReadInt();
            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static RedDot DeserializeRedDot(ByteBuf _buf)
        {
            return new Tables.RedDot(_buf);
        }

        /// <summary>
        /// 节点ID
        /// </summary>
        public ERedDotKey Id { private set; get; }
        /// <summary>
        /// 父节点ID(空=根节点)
        /// </summary>
        public ERedDotKey? ParentId { private set; get; }
        /// <summary>
        /// 显示模式
        /// </summary>
        public ERedDotDisplayMode DisplayMode { private set; get; }
        /// <summary>
        /// 清理策略
        /// </summary>
        public ERedDotCleanStrategy CleanStrategy { private set; get; }
        public const int __ID__ = 2013705889;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            
            PostResolveRef();
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ParentId:" + ParentId + ","
            + "DisplayMode:" + DisplayMode + ","
            + "CleanStrategy:" + CleanStrategy + ","
            + "}";
        }

        partial void PostInit();
        partial void PostResolveRef();
    }
}
