
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Hotfix.Game.Tables
{
    public sealed partial class RedDot : BeanBase
    {
        public RedDot(ERedDotKey Id, ERedDotKey? ParentId, ERedDotDisplayMode DisplayMode, ERedDotCleanStrategy CleanStrategy) 
        {
            this.Id = Id;
            this.ParentId = ParentId;
            this.DisplayMode = DisplayMode;
            this.CleanStrategy = CleanStrategy;
            PostInit();
        }

        public RedDot(JSONNode _buf)
        {
            { if(!_buf["Id"].IsNumber) { throw new SerializationException(); }  Id = (ERedDotKey)_buf["Id"].AsInt; }
            { var _j = _buf["ParentId"]; if (_j.Tag != JSONNodeType.None && _j.Tag != JSONNodeType.NullValue) { { if(!_j.IsNumber) { throw new SerializationException(); }  ParentId = (ERedDotKey?)_j.AsInt; } } else { ParentId = null; } }
            { if(!_buf["DisplayMode"].IsNumber) { throw new SerializationException(); }  DisplayMode = (ERedDotDisplayMode)_buf["DisplayMode"].AsInt; }
            { if(!_buf["CleanStrategy"].IsNumber) { throw new SerializationException(); }  CleanStrategy = (ERedDotCleanStrategy)_buf["CleanStrategy"].AsInt; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static RedDot DeserializeRedDot(JSONNode _buf)
        {
            return new Tables.RedDot(_buf);
        }

        /// <summary>
        /// 节点ID
        /// </summary>
        public ERedDotKey Id { private set; get; }
        /// <summary>
        /// 父节点ID(空=根节点)
        /// </summary>
        public ERedDotKey? ParentId { private set; get; }
        /// <summary>
        /// 显示模式
        /// </summary>
        public ERedDotDisplayMode DisplayMode { private set; get; }
        /// <summary>
        /// 清理策略
        /// </summary>
        public ERedDotCleanStrategy CleanStrategy { private set; get; }
        public const int __ID__ = 2013705889;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "ParentId:" + ParentId + ","
            + "DisplayMode:" + DisplayMode + ","
            + "CleanStrategy:" + CleanStrategy + ","
            + "}";
        }

        partial void PostInit();
    }
}
