//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// Sound 数据类
    /// </summary>
    public sealed partial class Sound : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = 343291974;

        /// <summary> ID </summary>
        public int Id { private set; get; }

        /// <summary> 声音所属组 </summary>
        public string GroupName { private set; get; }

        /// <summary> 声音所在的路径 </summary>
        public string Path { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 Sound 实例(外部使用)
        /// </summary>
        /// <param name="id">ID</param>
        /// <param name="groupName">声音所属组</param>
        /// <param name="path">声音所在的路径</param>
        public Sound(int id, string groupName, string path) 
        {
            Id = id;
            GroupName = groupName;
            Path = path;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 Sound 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private Sound(JSONNode node)
        {
            { if(!node["id"].IsNumber) { throw new SerializationException(); }  Id = node["id"]; }
            { if(!node["groupName"].IsString) { throw new SerializationException(); }  GroupName = node["groupName"]; }
            { if(!node["path"].IsString) { throw new SerializationException(); }  Path = node["path"]; }

            // Localization Key Begin
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 Sound 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 Sound</returns>
        public static Sound DeserializeSound(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "id:"        + Id        + ","
                   + "groupName:" + GroupName + ","
                   + "path:"      + Path      + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}