
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Hotfix.Game.Tables.Tables
{
    public sealed partial class Sound : BeanBase
    {
        public Sound(int Id, string GroupName, string Path) 
        {
            this.Id = Id;
            this.GroupName = GroupName;
            this.Path = Path;
            PostInit();
        }

        public Sound(ByteBuf _buf) 
        {
            Id = _buf.ReadInt();
            GroupName = _buf.ReadString();
            Path = _buf.ReadString();
            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static Sound DeserializeSound(ByteBuf _buf)
        {
            return new Tables.Sound(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 声音所属组
        /// </summary>
        public string GroupName { private set; get; }
        /// <summary>
        /// 声音所在的路径
        /// </summary>
        public string Path { private set; get; }
        public const int __ID__ = 343291974;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            PostResolveRef();
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "groupName:" + GroupName + ","
            + "path:" + Path + ","
            + "}";
        }

        partial void PostInit();
        partial void PostResolveRef();
    }
}
