//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// SoundGroup 数据类
    /// </summary>
    public sealed partial class SoundGroup : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = 1346243033;

        /// <summary> 声音组ID </summary>
        public ESoundGroup Id { private set; get; }

        /// <summary> 默认静音 </summary>
        public bool Mute { private set; get; }

        /// <summary> 默认音量 </summary>
        public float Volume { private set; get; }

        /// <summary> 播放代理数 </summary>
        public int AgentCount { private set; get; }

        /// <summary> 允许同优先级替换 </summary>
        public bool AllowBeReplacedBySamePriority { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 SoundGroup 实例(外部使用)
        /// </summary>
        /// <param name="id">声音组ID</param>
        /// <param name="mute">默认静音</param>
        /// <param name="volume">默认音量</param>
        /// <param name="agentCount">播放代理数</param>
        /// <param name="allowBeReplacedBySamePriority">允许同优先级替换</param>
        public SoundGroup(ESoundGroup id, bool mute, float volume, int agentCount, bool allowBeReplacedBySamePriority) 
        {
            Id = id;
            Mute = mute;
            Volume = volume;
            AgentCount = agentCount;
            AllowBeReplacedBySamePriority = allowBeReplacedBySamePriority;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 SoundGroup 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private SoundGroup(JSONNode node)
        {
            { if(!node["Id"].IsNumber) { throw new SerializationException(); }  Id = (ESoundGroup)node["Id"].AsInt; }
            { if(!node["Mute"].IsBoolean) { throw new SerializationException(); }  Mute = node["Mute"]; }
            { if(!node["Volume"].IsNumber) { throw new SerializationException(); }  Volume = node["Volume"]; }
            { if(!node["AgentCount"].IsNumber) { throw new SerializationException(); }  AgentCount = node["AgentCount"]; }
            { if(!node["AllowBeReplacedBySamePriority"].IsBoolean) { throw new SerializationException(); }  AllowBeReplacedBySamePriority = node["AllowBeReplacedBySamePriority"]; }

            // Localization Key Begin
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 SoundGroup 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 SoundGroup</returns>
        public static SoundGroup DeserializeSoundGroup(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "Id:"                            + Id                            + ","
                   + "Mute:"                          + Mute                          + ","
                   + "Volume:"                        + Volume                        + ","
                   + "AgentCount:"                    + AgentCount                    + ","
                   + "AllowBeReplacedBySamePriority:" + AllowBeReplacedBySamePriority + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}