
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace Hotfix.Game.Tables.Tables
{
    public sealed partial class SoundGroup : BeanBase
    {
        public SoundGroup(ESoundGroup Id, bool Mute, float Volume, int AgentCount, bool AllowBeReplacedBySamePriority) 
        {
            this.Id = Id;
            this.Mute = Mute;
            this.Volume = Volume;
            this.AgentCount = AgentCount;
            this.AllowBeReplacedBySamePriority = AllowBeReplacedBySamePriority;
            PostInit();
        }

        public SoundGroup(ByteBuf _buf) 
        {
            Id = (ESoundGroup)_buf.ReadInt();
            Mute = _buf.ReadBool();
            Volume = _buf.ReadFloat();
            AgentCount = _buf.ReadInt();
            AllowBeReplacedBySamePriority = _buf.ReadBool();
            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static SoundGroup DeserializeSoundGroup(ByteBuf _buf)
        {
            return new Tables.SoundGroup(_buf);
        }

        /// <summary>
        /// 声音组ID
        /// </summary>
        public ESoundGroup Id { private set; get; }
        /// <summary>
        /// 默认静音
        /// </summary>
        public bool Mute { private set; get; }
        /// <summary>
        /// 默认音量
        /// </summary>
        public float Volume { private set; get; }
        /// <summary>
        /// 播放代理数
        /// </summary>
        public int AgentCount { private set; get; }
        /// <summary>
        /// 允许同优先级替换
        /// </summary>
        public bool AllowBeReplacedBySamePriority { private set; get; }
        public const int __ID__ = 1346243033;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            
            
            PostResolveRef();
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "Id:" + Id + ","
            + "Mute:" + Mute + ","
            + "Volume:" + Volume + ","
            + "AgentCount:" + AgentCount + ","
            + "AllowBeReplacedBySamePriority:" + AllowBeReplacedBySamePriority + ","
            + "}";
        }

        partial void PostInit();
        partial void PostResolveRef();
    }
}
