
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;
using Hotfix.Framework.Config;

namespace Hotfix.Game.Tables.Tables
{
    /// <summary>
    /// 实体组配置表
    /// </summary>
    public partial class TbEntityGroup : BaseDataTable<Tables.EntityGroup>
    {
        private readonly System.Func<System.Threading.Tasks.Task<JSONNode>> _loadFunc;        
        public TbEntityGroup(System.Func<System.Threading.Tasks.Task<JSONNode>> loadFunc)
        {
            _loadFunc = loadFunc;
        }
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            var jsonNode = await _loadFunc();
            DataList.Clear();
            LongKeyDataDict.Clear();
            StrKeyDataDict.Clear();
            foreach(var _ele in jsonNode.Children)
            {
                Tables.EntityGroup _v;
                { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::Hotfix.Game.Tables.Tables.EntityGroup.DeserializeEntityGroup(_ele);  }
                DataList.Add(_v);
                LongKeyDataDict.Add((int)_v.Id, _v);
                StrKeyDataDict.Add(_v.Id.ToString(), _v);
            }
            PostInit();
        }
    
        public void ResolveRef(TableManager tables)
        {
            foreach(var value in DataList)
            {
                value.ResolveRef(tables);
            }
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
            foreach(var v in DataList)
            {
                v.TranslateText(translator);
            }
        }




        partial void PostInit();
    }
}

