//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;
using Hotfix.Framework.Config;
using Cysharp.Threading.Tasks;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// 道具表
    /// </summary>
    public partial class TbItem : BaseDataTable<Item>
    {
        /// <summary>
        /// 取配置表 JSON 的加载委托（由 TableManager 注入，参数为表文件路径）
        /// </summary>
        private readonly Func<UniTask<JSONNode>> m_LoadFunc;

        /// <summary>
        /// 创建表实例
        /// </summary>
        /// <param name="loadFunc">取配置表 JSON 的加载委托</param>
        public TbItem(Func<UniTask<JSONNode>> loadFunc) => m_LoadFunc = loadFunc;

        /// <summary>
        /// 异步加载本表数据
        /// </summary>
        /// <remarks>从 loader 取 JSON、清空字典、逐行反序列化，完成后调用 PostInit</remarks>
        public override async UniTask LoadAsync()
        {
            var jsonNode = await m_LoadFunc();

            DataList.Clear();
            LongKeyDataDict.Clear();
            StrKeyDataDict.Clear();

            foreach(var node in jsonNode.Children)
            {
                if (!node.IsObject) throw new SerializationException();  
                var item = Item.DeserializeItem(node);
                DataList.Add(item);
                LongKeyDataDict.Add(item.Id, item);
                StrKeyDataDict.Add(item.Id.ToString(), item);
            }

            OnInit();
        }

        /// <summary>
        /// 解析本表内所有跨表引用（把引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public void ResolveRef(TableManager tableManager)
        {
            foreach(var value in DataList)
            {
                value.ResolveRef(tableManager);
            }
        }

        /// <summary>
        /// 用指定翻译器刷新本表所有多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
            foreach(var v in DataList)
            {
                v.TranslateText(translator);
            }
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成一些给该表预计算、排序、建字典索引等"只靠本表数据就能完成"的预处理收尾工作
        /// </summary>
        partial void OnInit();
    }
}