
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Hotfix.Framework.Config;

namespace Hotfix.Game.Tables.Tables
{
    /// <summary>
    /// 声音组配置表
    /// </summary>
    public partial class TbSoundGroup : BaseDataTable<Tables.SoundGroup>
    {
        private readonly System.Func<System.Threading.Tasks.Task<ByteBuf>> _loadFunc;

        public TbSoundGroup(System.Func<System.Threading.Tasks.Task<ByteBuf>> loadFunc)
        {
            _loadFunc = loadFunc;
        }

        public override async System.Threading.Tasks.Task LoadAsync()
        {
            ByteBuf _buf = await _loadFunc();
            DataList.Clear();
            LongKeyDataDict.Clear();
            StrKeyDataDict.Clear();
            for(int n = _buf.ReadSize() ; n > 0 ; --n)
            {
                Tables.SoundGroup _v;
                _v = global::Hotfix.Game.Tables.Tables.SoundGroup.DeserializeSoundGroup(_buf);
                DataList.Add(_v);
                LongKeyDataDict.Add((long)_v.Id, _v);
                StrKeyDataDict.Add(_v.Id.ToString(), _v);
            }
            PostInit();
        }


        public void ResolveRef(TableManager tables)
        {
            foreach(var value in DataList)
            {
                value.ResolveRef(tables);
            }
            PostResolveRef();
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
            foreach(var v in DataList)
            {
                v.TranslateText(translator);
            }
        }


        partial void PostInit();
        partial void PostResolveRef();
    }
}
