
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Hotfix.Game.Config.Tables
{
    public sealed partial class UIConfig : BeanBase
    {
        public UIConfig(string Name, EUILayer Layer, EUITweenType TweenType, float TweenDuration, bool AdjustNotch, bool PauseCoveredUI) 
        {
            this.Name = Name;
            this.Layer = Layer;
            this.TweenType = TweenType;
            this.TweenDuration = TweenDuration;
            this.AdjustNotch = AdjustNotch;
            this.PauseCoveredUI = PauseCoveredUI;
            PostInit();
        }

        public UIConfig(JSONNode _buf)
        {
            { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
            { if(!_buf["Layer"].IsNumber) { throw new SerializationException(); }  Layer = (EUILayer)_buf["Layer"].AsInt; }
            { if(!_buf["TweenType"].IsNumber) { throw new SerializationException(); }  TweenType = (EUITweenType)_buf["TweenType"].AsInt; }
            { if(!_buf["TweenDuration"].IsNumber) { throw new SerializationException(); }  TweenDuration = _buf["TweenDuration"]; }
            { if(!_buf["AdjustNotch"].IsBoolean) { throw new SerializationException(); }  AdjustNotch = _buf["AdjustNotch"]; }
            { if(!_buf["PauseCoveredUI"].IsBoolean) { throw new SerializationException(); }  PauseCoveredUI = _buf["PauseCoveredUI"]; }

            // Localization Key Begin
            // Localization Key End
            PostInit();
        }

        public static UIConfig DeserializeUIConfig(JSONNode _buf)
        {
            return new Tables.UIConfig(_buf);
        }

        /// <summary>
        /// 界面名称（主键）
        /// </summary>
        public string Name { private set; get; }
        /// <summary>
        /// 界面层级
        /// </summary>
        public EUILayer Layer { private set; get; }
        /// <summary>
        /// 动画类型
        /// </summary>
        public EUITweenType TweenType { private set; get; }
        /// <summary>
        /// 动画时长（秒）
        /// </summary>
        public float TweenDuration { private set; get; }
        /// <summary>
        /// 是否适配刘海
        /// </summary>
        public bool AdjustNotch { private set; get; }
        /// <summary>
        /// 被遮挡时是否暂停
        /// </summary>
        public bool PauseCoveredUI { private set; get; }
        public const int __ID__ = -910817217;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
        }

        public override string ToString()
        {
            return "{ "
            + "Name:" + Name + ","
            + "Layer:" + Layer + ","
            + "TweenType:" + TweenType + ","
            + "TweenDuration:" + TweenDuration + ","
            + "AdjustNotch:" + AdjustNotch + ","
            + "PauseCoveredUI:" + PauseCoveredUI + ","
            + "}";
        }

        partial void PostInit();
    }
}
