//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Luban;
using SimpleJSON;

// ReSharper disable once CheckNamespace
namespace Hotfix.Game.Config
{
    /// <summary>
    /// UIConfig 数据类
    /// </summary>
    public sealed partial class UIConfig : BeanBase
    {
        /// <summary> 本 bean 的类型标识常量 </summary>
        public const int __ID__ = -910817217;

        /// <summary> 界面名称（主键） </summary>
        public string Name { private set; get; }

        /// <summary> 界面层级 </summary>
        public EUILayer Layer { private set; get; }

        /// <summary> 动画类型 </summary>
        public EUITweenType TweenType { private set; get; }

        /// <summary> 动画时长（秒） </summary>
        public float TweenDuration { private set; get; }

        /// <summary> 是否适配刘海:<br/>全屏界面一般为true<br/>弹窗一般为false </summary>
        public bool AdjustNotch { private set; get; }

        /// <summary> 被覆盖时是否暂停 </summary>
        public bool PauseCoveredUI { private set; get; }

        /// <summary> 是否模糊:<br/>全屏界面一般为false<br/>弹窗一般为true </summary>
        public bool Blur { private set; get; }

        /// <summary> 获取 bean 类型标识 </summary>
        public override int GetTypeId() => __ID__;

        /// <summary>
        /// 创建 UIConfig 实例(外部使用)
        /// </summary>
        /// <param name="Name">界面名称（主键）</param>
        /// <param name="Layer">界面层级</param>
        /// <param name="TweenType">动画类型</param>
        /// <param name="TweenDuration">动画时长（秒）</param>
        /// <param name="AdjustNotch">是否适配刘海:<br/>全屏界面一般为true<br/>弹窗一般为false</param>
        /// <param name="PauseCoveredUI">被覆盖时是否暂停</param>
        /// <param name="Blur">是否模糊:<br/>全屏界面一般为false<br/>弹窗一般为true</param>
        public UIConfig(string Name, EUILayer Layer, EUITweenType TweenType, float TweenDuration, bool AdjustNotch, bool PauseCoveredUI, bool Blur) 
        {
            Name = Name;
            Layer = Layer;
            TweenType = TweenType;
            TweenDuration = TweenDuration;
            AdjustNotch = AdjustNotch;
            PauseCoveredUI = PauseCoveredUI;
            Blur = Blur;
            OnInit();
        }

        /// <summary>
        /// 从 JSONNode 反序列化创建 UIConfig 实例(内部序列化使用)
        /// </summary>
        /// <param name="node">配置数据节点</param>
        private UIConfig(JSONNode node)
        {
            { if(!node["Name"].IsString) { throw new SerializationException(); }  Name = node["Name"]; }
            { if(!node["Layer"].IsNumber) { throw new SerializationException(); }  Layer = (EUILayer)node["Layer"].AsInt; }
            { if(!node["TweenType"].IsNumber) { throw new SerializationException(); }  TweenType = (EUITweenType)node["TweenType"].AsInt; }
            { if(!node["TweenDuration"].IsNumber) { throw new SerializationException(); }  TweenDuration = node["TweenDuration"]; }
            { if(!node["AdjustNotch"].IsBoolean) { throw new SerializationException(); }  AdjustNotch = node["AdjustNotch"]; }
            { if(!node["PauseCoveredUI"].IsBoolean) { throw new SerializationException(); }  PauseCoveredUI = node["PauseCoveredUI"]; }
            { if(!node["Blur"].IsBoolean) { throw new SerializationException(); }  Blur = node["Blur"]; }

            // Localization Key Begin
            // Localization Key End
            OnInit();
        }

        /// <summary>
        /// 反序列化创建 UIConfig 实例
        /// </summary>
        /// <param name="node">配置数据节点</param>
        /// <returns>反序列化后的 UIConfig</returns>
        public static UIConfig DeserializeUIConfig(JSONNode node) => new(node);

        /// <summary>
        /// 解析本 bean 的跨表引用（引用的 id 换成实际对象）
        /// </summary>
        /// <param name="tableManager">表管理器，用于跨表查找</param>
        public  void ResolveRef(TableManager tableManager)
        {
        }

        /// <summary>
        /// 用指定翻译器刷新本 bean 的多语言字段
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        public void TranslateText(Func<string, string, string> translator)
        {
        }

        /// <summary>
        /// 返回本对象的字段字符串表示
        /// </summary>
        public override string ToString()
        {
            return "{ "
                   + "Name:"           + Name           + ","
                   + "Layer:"          + Layer          + ","
                   + "TweenType:"      + TweenType      + ","
                   + "TweenDuration:"  + TweenDuration  + ","
                   + "AdjustNotch:"    + AdjustNotch    + ","
                   + "PauseCoveredUI:" + PauseCoveredUI + ","
                   + "Blur:"           + Blur           + ","
                   + "}";
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成构造完成后的自定义预处理收尾工作，
        /// </summary>
        partial void OnInit();
    }
}