// <auto-generated>
//	本代码由FGUI插件CSharpCodeGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using System;
using Cysharp.Threading.Tasks;
using FairyGUI;
using FairyGUI.Utils;
using Hotfix.Framework.UI;
using Hotfix.Framework.Core;
using AOT.Framework.Core.Log;
using Hotfix.Framework.Event;
using Hotfix.Framework.Timer;

namespace Hotfix.Game.UI
{
    public partial class CompTypeItem : GButton
    {
        private TimerRegister m_TimerRegister;     // 计时器注册器
        private EventRegister m_EventRegister;     // 业务逻辑事件注册器
        private FuiEventRegister m_UIEventRegister;// UI事件注册器

		private Controller button;

		public const string URL = "ui://a3awyna7l50q4";

		/// <summary>
		/// button
		/// </summary>
		private enum Ebutton
		{
			/// <summary>
			/// up
			/// </summary>
			Up = 0,
			/// <summary>
			/// down
			/// </summary>
			Down = 1,
		}

		/// <summary>
		/// 设置 button 控制器状态
		/// </summary>
		private void SetController(Ebutton ebutton) => button.SetSelectedIndex((int) ebutton);

		/// <summary>
		/// 组件被构造时由FUI自动调用
		/// </summary>
		/// <param name="xml">组件描述结构</param>
		public override void ConstructFromXML(XML xml)
		{
			base.ConstructFromXML(xml);
			InitUIComp();
			m_UIEventRegister = FuiEventRegister.Create();
			m_EventRegister = EventRegister.Create();
			m_TimerRegister = TimerRegister.Create();
			InitUIEvent();
			OnInit();
		}

        /// <summary>
        /// UI组件初始化
        /// </summary>
        private void InitUIComp()
        {
			button = GetController("button");
        }

        /// <summary>
        /// UI组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {

        }

        /// <summary>
        /// UI组件销毁
        /// </summary>
        public override void Dispose()
        {
            FuLogger.LogInfo($"销毁界面组件-{GetType().Name}");
            OnDispose();
            m_UIEventRegister?.Release();
            m_EventRegister?.Release();
            m_TimerRegister?.Release();
            base.Dispose();
        }

        #region UI事件处理

        protected void AddUIListener(EventListener listener, EventCallback1 callback) => m_UIEventRegister.AddUIListener(listener, callback);

        protected void SetUIListener(EventListener listener, EventCallback1 callback) => m_UIEventRegister.SetUIListener(listener, callback);

        protected void RemoveUIListener(EventListener listener, EventCallback1 callback) => m_UIEventRegister.RemoveUIListener(listener, callback);

        protected void ClearUIListener(EventListener listener) => m_UIEventRegister.ClearUIListener(listener);

        protected void ClearAllUIListener() => m_UIEventRegister.ClearAllUIListener();

        #endregion

        #region 业务逻辑事件处理

        protected void Subscribe(string eventId, EventHandler<GameEventArgs> handler) => m_EventRegister.Subscribe(eventId, handler);

        protected void UnSubscribe(string eventId, EventHandler<GameEventArgs> handler) => m_EventRegister.UnSubscribe(eventId, handler);

        protected void Broadcast(string eventId, GameEventArgs e) => m_EventRegister.Broadcast(eventId, e);

        protected void Broadcast(object sender, string eventId) => m_EventRegister.Broadcast(sender, eventId);

        protected void BroadcastNow(object sender, GameEventArgs e) => m_EventRegister.BroadcastNow(sender, e);

        protected void UnSubscribeAll() => m_EventRegister.UnSubscribeAll();

        #endregion

        #region 计时器

        protected void StartCountdownTimer(float duration, Action finishCallBack = null, Action updateCallBack = null, PlayerLoopTiming playerLoopTiming = PlayerLoopTiming.Update, bool ignoreTimeScale = false)
        {
            m_TimerRegister.StartCountdownTimer(duration, finishCallBack, updateCallBack, playerLoopTiming, ignoreTimeScale);
        }

        protected void StartIntervalTimer(float interval, Action intervalCallback, int repeatCount = -1, bool immediate = false, bool ignoreTimeScale = false)
        {
            m_TimerRegister.StartIntervalTimer(interval, intervalCallback, repeatCount, immediate, ignoreTimeScale);
        }

        protected void StartFrameTimer(int frameInterval, Action intervalCallback, int repeatCount = -1, bool immediate = false, PlayerLoopTiming playerLoopTiming = PlayerLoopTiming.Update)
        {
            m_TimerRegister.StartFrameTimer(frameInterval, intervalCallback, repeatCount, immediate, playerLoopTiming);
        }

        protected void PauseTimer(int timerId) => m_TimerRegister.PauseTimer(timerId);

        protected void ResumeTimer(int timerId) => m_TimerRegister.ResumeTimer(timerId);

        protected void StopTimer(int timerId) => m_TimerRegister.StopTimer(timerId);

        protected void PauseAllTimers() => m_TimerRegister.PauseAllTimers();

        protected void ResumeAllTimers() => m_TimerRegister.ResumeAllTimers();

        protected void StopAllTimers() => m_TimerRegister.StopAllTimers();

        protected bool IsTimerExist(int timerId) => m_TimerRegister.IsTimerExist(timerId);

        protected bool IsTimerPaused(int timerId) => m_TimerRegister.IsTimerPaused(timerId);

        #endregion
    }
}
