
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotfix.Config
{
    /// <summary>
    /// 本地化多语言Key列表
    /// </summary>
    public static class LanguageKey
    {
        /// <summary>
        /// 关于更多
        /// </summary>
        public const string about = "about";

        /// <summary>
        /// 继续上一次游戏
        /// </summary>
        public const string continue_game = "continue_game";

        /// <summary>
        /// 取消
        /// </summary>
        public const string exit_cancel = "exit_cancel";

        /// <summary>
        /// 退出游戏
        /// </summary>
        public const string exit_game = "exit_game";

        /// <summary>
        /// 始终需要确认
        /// </summary>
        public const string exit_label = "exit_label";

        /// <summary>
        /// 确定
        /// </summary>
        public const string exit_submit = "exit_submit";

        /// <summary>
        /// 是否退出游戏？
        /// </summary>
        public const string exit_title = "exit_title";

        /// <summary>
        /// 画廊设置
        /// </summary>
        public const string gallerty = "gallerty";

        /// <summary>
        /// 读取游戏
        /// </summary>
        public const string load_game = "load_game";

        /// <summary>
        /// 开始游戏
        /// </summary>
        public const string pop_start_game = "pop_start_game";

        /// <summary>
        /// 开始游戏
        /// </summary>
        public const string start_game = "start_game";

        /// <summary>
        /// 系统设置
        /// </summary>
        public const string system_setting = "system_setting";

        /// <summary>
        /// 您已解锁“独自享受的日常”路线！恭喜您！这是只属于您一人的物语！
        /// </summary>
        public const string text_achievement_content_1 = "text_achievement_content_1";

        /// <summary>
        /// 您已赢得巫女玲奈的芳心，并肩负起守护神社的责任！（大概吧）
        /// </summary>
        public const string text_achievement_content_2 = "text_achievement_content_2";

        /// <summary>
        /// 成就未解锁
        /// </summary>
        public const string text_achievement_cover = "text_achievement_cover";

        /// <summary>
        /// 独自享受的日常
        /// </summary>
        public const string text_achievement_name_01 = "text_achievement_name_01";

        /// <summary>
        /// 神社的守护者
        /// </summary>
        public const string text_achievement_name_02 = "text_achievement_name_02";

        /// <summary>
        /// 紧急回避模式
        /// </summary>
        public const string ui_nav_advdance = "ui_nav_advdance";

        /// <summary>
        /// 全文
        /// </summary>
        public const string ui_nav_alltext = "ui_nav_alltext";

        /// <summary>
        /// 鉴赏模式
        /// </summary>
        public const string ui_nav_appreciation = "ui_nav_appreciation";

        /// <summary>
        /// 自动模式
        /// </summary>
        public const string ui_nav_auto = "ui_nav_auto";

        /// <summary>
        /// 选项后取消自动播放
        /// </summary>
        public const string ui_nav_autocancel = "ui_nav_autocancel";

        /// <summary>
        /// 自动存档
        /// </summary>
        public const string ui_nav_autodoc = "ui_nav_autodoc";

        /// <summary>
        /// 自动播放
        /// </summary>
        public const string ui_nav_autoplay = "ui_nav_autoplay";

        /// <summary>
        /// 自动模式速度
        /// </summary>
        public const string ui_nav_autospeed = "ui_nav_autospeed";

        /// <summary>
        /// BGM
        /// </summary>
        public const string ui_nav_bgm = "ui_nav_bgm";

        /// <summary>
        /// 截图保存
        /// </summary>
        public const string ui_nav_capture = "ui_nav_capture";

        /// <summary>
        /// 语音音量
        /// </summary>
        public const string ui_nav_chat = "ui_nav_chat";

        /// <summary>
        /// 语音设置
        /// </summary>
        public const string ui_nav_chatsetting = "ui_nav_chatsetting";

        /// <summary>
        /// 鼠标左击
        /// </summary>
        public const string ui_nav_clickleft = "ui_nav_clickleft";

        /// <summary>
        /// 鼠标右击
        /// </summary>
        public const string ui_nav_clickright = "ui_nav_clickright";

        /// <summary>
        /// 关闭窗口
        /// </summary>
        public const string ui_nav_close = "ui_nav_close";

        /// <summary>
        /// 删除存档时确认
        /// </summary>
        public const string ui_nav_confirmdeldoc = "ui_nav_confirmdeldoc";

        /// <summary>
        /// 退出游戏时确认
        /// </summary>
        public const string ui_nav_confirmexit = "ui_nav_confirmexit";

        /// <summary>
        /// 读取游戏时确认
        /// </summary>
        public const string ui_nav_confirmload = "ui_nav_confirmload";

        /// <summary>
        /// 是否新建存档?
        /// </summary>
        public const string ui_nav_confirmnew = "ui_nav_confirmnew";

        /// <summary>
        /// 返回标题时确认
        /// </summary>
        public const string ui_nav_confirmreturn = "ui_nav_confirmreturn";

        /// <summary>
        /// 保存游戏时确认
        /// </summary>
        public const string ui_nav_confirmsave = "ui_nav_confirmsave";

        /// <summary>
        /// 跳转场景时确认
        /// </summary>
        public const string ui_nav_confirmswitch = "ui_nav_confirmswitch";

        /// <summary>
        /// 默认
        /// </summary>
        public const string ui_nav_default = "ui_nav_default";

        /// <summary>
        /// 恢复默认
        /// </summary>
        public const string ui_nav_defaultbtn = "ui_nav_defaultbtn";

        /// <summary>
        /// 删除
        /// </summary>
        public const string ui_nav_del = "ui_nav_del";

        /// <summary>
        /// 是否删除存档?
        /// </summary>
        public const string ui_nav_deldoc = "ui_nav_deldoc";

        /// <summary>
        /// 删除
        /// </summary>
        public const string ui_nav_delete = "ui_nav_delete";

        /// <summary>
        /// 这里是示例，展示自动模式下文字生成速度
        /// </summary>
        public const string ui_nav_demo = "ui_nav_demo";

        /// <summary>
        /// 示例文本
        /// </summary>
        public const string ui_nav_demotest = "ui_nav_demotest";

        /// <summary>
        /// 清除按键
        /// </summary>
        public const string ui_nav_disable = "ui_nav_disable";

        /// <summary>
        /// 存档
        /// </summary>
        public const string ui_nav_doc = "ui_nav_doc";

        /// <summary>
        /// 游戏存档管理
        /// </summary>
        public const string ui_nav_document = "ui_nav_document";

        /// <summary>
        /// 游戏结束时自动存档
        /// </summary>
        public const string ui_nav_endsave = "ui_nav_endsave";

        /// <summary>
        /// 离开游戏
        /// </summary>
        public const string ui_nav_exit = "ui_nav_exit";

        /// <summary>
        /// 快速模式
        /// </summary>
        public const string ui_nav_fast = "ui_nav_fast";

        /// <summary>
        /// 选项后取消快速模式
        /// </summary>
        public const string ui_nav_fastcancel = "ui_nav_fastcancel";

        /// <summary>
        /// 快速存档
        /// </summary>
        public const string ui_nav_fastdoc = "ui_nav_fastdoc";

        /// <summary>
        /// 快进已读
        /// </summary>
        public const string ui_nav_fastread = "ui_nav_fastread";

        /// <summary>
        /// 快速模式速度
        /// </summary>
        public const string ui_nav_fastspeed = "ui_nav_fastspeed";

        /// <summary>
        /// 全屏
        /// </summary>
        public const string ui_nav_full = "ui_nav_full";

        /// <summary>
        /// 渐变效果
        /// </summary>
        public const string ui_nav_gradienteffect = "ui_nav_gradienteffect";

        /// <summary>
        /// 灰暗
        /// </summary>
        public const string ui_nav_gray = "ui_nav_gray";

        /// <summary>
        /// 仅已读
        /// </summary>
        public const string ui_nav_hasread = "ui_nav_hasread";

        /// <summary>
        /// 高速模式
        /// </summary>
        public const string ui_nav_highspeed = "ui_nav_highspeed";

        /// <summary>
        /// 历史记录
        /// </summary>
        public const string ui_nav_history = "ui_nav_history";

        /// <summary>
        /// 键盘设置
        /// </summary>
        public const string ui_nav_keyboard = "ui_nav_keyboard";

        /// <summary>
        /// 文字显示途中鼠标左击跳过
        /// </summary>
        public const string ui_nav_leftclick = "ui_nav_leftclick";

        /// <summary>
        /// 明亮
        /// </summary>
        public const string ui_nav_light = "ui_nav_light";

        /// <summary>
        /// 读档
        /// </summary>
        public const string ui_nav_load = "ui_nav_load";

        /// <summary>
        /// 是否加载存档
        /// </summary>
        public const string ui_nav_loaddoc = "ui_nav_loaddoc";

        /// <summary>
        /// 长按鼠标左键可以快进文本
        /// </summary>
        public const string ui_nav_longclick = "ui_nav_longclick";

        /// <summary>
        /// 语音播放时降低BGM
        /// </summary>
        public const string ui_nav_lowbgm = "ui_nav_lowbgm";

        /// <summary>
        /// 最小化
        /// </summary>
        public const string ui_nav_min = "ui_nav_min";

        /// <summary>
        /// 播放语音
        /// </summary>
        public const string ui_nav_music = "ui_nav_music";

        /// <summary>
        /// 新建存档
        /// </summary>
        public const string ui_nav_newdoc = "ui_nav_newdoc";

        /// <summary>
        /// 由新到旧
        /// </summary>
        public const string ui_nav_newold = "ui_nav_newold";

        /// <summary>
        /// 下一个选择
        /// </summary>
        public const string ui_nav_next = "ui_nav_next";

        /// <summary>
        /// 否
        /// </summary>
        public const string ui_nav_no = "ui_nav_no";

        /// <summary>
        /// 暂无存档
        /// </summary>
        public const string ui_nav_nodata = "ui_nav_nodata";

        /// <summary>
        /// 无效
        /// </summary>
        public const string ui_nav_noeffect = "ui_nav_noeffect";

        /// <summary>
        /// 不播放
        /// </summary>
        public const string ui_nav_noplay = "ui_nav_noplay";

        /// <summary>
        /// 普通
        /// </summary>
        public const string ui_nav_normal = "ui_nav_normal";

        /// <summary>
        /// 不显示进行语音播放的文本
        /// </summary>
        public const string ui_nav_noshowtext = "ui_nav_noshowtext";

        /// <summary>
        /// 由旧到新
        /// </summary>
        public const string ui_nav_oldnew = "ui_nav_oldnew";

        /// <summary>
        /// 中断游戏
        /// </summary>
        public const string ui_nav_pause = "ui_nav_pause";

        /// <summary>
        /// 画面
        /// </summary>
        public const string ui_nav_pic = "ui_nav_pic";

        /// <summary>
        /// 播放
        /// </summary>
        public const string ui_nav_play = "ui_nav_play";

        /// <summary>
        /// 播放速度
        /// </summary>
        public const string ui_nav_playspeed = "ui_nav_playspeed";

        /// <summary>
        /// 上一个选择
        /// </summary>
        public const string ui_nav_pre = "ui_nav_pre";

        /// <summary>
        /// 快速读档
        /// </summary>
        public const string ui_nav_quickload = "ui_nav_quickload";

        /// <summary>
        /// 快速存档
        /// </summary>
        public const string ui_nav_quicksave = "ui_nav_quicksave";

        /// <summary>
        /// 退出系统设置
        /// </summary>
        public const string ui_nav_returnsetting = "ui_nav_returnsetting";

        /// <summary>
        /// 是否返回标题页?
        /// </summary>
        public const string ui_nav_returntitle = "ui_nav_returntitle";

        /// <summary>
        /// 返回标题页
        /// </summary>
        public const string ui_nav_returntotitle = "ui_nav_returntotitle";

        /// <summary>
        /// 存档
        /// </summary>
        public const string ui_nav_saved = "ui_nav_saved";

        /// <summary>
        /// 场景设置
        /// </summary>
        public const string ui_nav_scene = "ui_nav_scene";

        /// <summary>
        /// 出现选项时自动存档
        /// </summary>
        public const string ui_nav_selectsave = "ui_nav_selectsave";

        /// <summary>
        /// 系统设置
        /// </summary>
        public const string ui_nav_setting = "ui_nav_setting";

        /// <summary>
        /// 设定界面
        /// </summary>
        public const string ui_nav_settings = "ui_nav_settings";

        /// <summary>
        /// 剧情开始时自动存档
        /// </summary>
        public const string ui_nav_startsave = "ui_nav_startsave";

        /// <summary>
        /// 结束游戏
        /// </summary>
        public const string ui_nav_stop = "ui_nav_stop";

        /// <summary>
        /// 切换画面模式
        /// </summary>
        public const string ui_nav_switch = "ui_nav_switch";

        /// <summary>
        /// 是否要切换语言，并关闭游戏？（请先做好数据存档哦）
        /// </summary>
        public const string ui_nav_switchlang = "ui_nav_switchlang";

        /// <summary>
        /// 文本设置
        /// </summary>
        public const string ui_nav_text = "ui_nav_text";

        /// <summary>
        /// 文本快进
        /// </summary>
        public const string ui_nav_textfast = "ui_nav_textfast";

        /// <summary>
        /// 文本速度
        /// </summary>
        public const string ui_nav_textspeed = "ui_nav_textspeed";

        /// <summary>
        /// 文本类型
        /// </summary>
        public const string ui_nav_texttype = "ui_nav_texttype";

        /// <summary>
        /// 返回标题
        /// </summary>
        public const string ui_nav_title = "ui_nav_title";

        /// <summary>
        /// 打开工具栏
        /// </summary>
        public const string ui_nav_tool = "ui_nav_tool";

        /// <summary>
        /// 触摸设置
        /// </summary>
        public const string ui_nav_touch = "ui_nav_touch";

        /// <summary>
        /// 音效设置
        /// </summary>
        public const string ui_nav_voice = "ui_nav_voice";

        /// <summary>
        /// 音量设置
        /// </summary>
        public const string ui_nav_voicesetting = "ui_nav_voicesetting";

        /// <summary>
        /// 主音量
        /// </summary>
        public const string ui_nav_volume = "ui_nav_volume";

        /// <summary>
        /// 音量测试
        /// </summary>
        public const string ui_nav_volumetest = "ui_nav_volumetest";

        /// <summary>
        /// 点击滚轮
        /// </summary>
        public const string ui_nav_wheel = "ui_nav_wheel";

        /// <summary>
        /// 窗口
        /// </summary>
        public const string ui_nav_window = "ui_nav_window";

        /// <summary>
        /// 是
        /// </summary>
        public const string ui_nav_yes = "ui_nav_yes";

    }
}

