//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotfix.Game.Config
{
    /// <summary>
    /// 本地化多语言Key列表
    /// </summary>
    public static class L10nKey
    {
        /// <summary>
        /// 取消
        /// </summary>
        public const string common_exit_cancel = "common_exit_cancel";

        /// <summary>
        /// 确定
        /// </summary>
        public const string common_exit_submit = "common_exit_submit";

    }
}