//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotfix.Game.Config
{
    /// <summary>
    /// 本地化多语言Key列表
    /// </summary>
    public static class LanguageKey
    {
        /// <summary>
        /// 取消
        /// </summary>
        public const string common_exit_cancel = "common_exit_cancel";

        /// <summary>
        /// 确定
        /// </summary>
        public const string common_exit_submit = "common_exit_submit";

    }
}