// <auto-generated>
//	本代码由FGUI插件CSharpCodeGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;
using UnityEngine;
using FuFramework.Core.Runtime;

namespace Launcher
{
    /// <summary>
    /// 所有自定义组件的绑定器。由FUI导出时自动生成。
    /// </summary>
    public static class CustomCompBind
    {
        /// <summary>
        /// 绑定所有自定义组件
        /// </summary>
        public static void BindAll()
        {
			BindLauncher();
        }

		/// <summary>
		/// 绑定Launcher包下的自定义组件
		/// </summary>
		private static void BindLauncher()
		{
			FuLogger.LogInfo("绑定包-{Launcher}下的所有自定义组件");
			UIObjectFactory.SetPackageItemExtension(CompBagItemInfoTest.URL, typeof(CompBagItemInfoTest));
		}
    }
}
