// <auto-generated>
//	本代码由FGUI插件CSharpCodeGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Launcher
{
    public class WinLauncher
    {
        public GComponent m_View;

		public Controller IsNeedUpgrade;
		public Controller IsDownloading;
		public GTextField txtTips;
		public GProgressBar progressBar;
		public GButton btnOk;
		public GRichTextField txtContent;

		/// <summary>
		/// 是否需要更新
		/// </summary>
		public enum EIsNeedUpgrade
		{
			/// <summary>
			/// 不需要
			/// </summary>
			No = 0,
			/// <summary>
			/// 需要
			/// </summary>
			Yes = 1,
		}

		/// <summary>
		/// 是否下载中
		/// </summary>
		public enum EIsDownloading
		{
			/// <summary>
			/// 否
			/// </summary>
			No = 0,
			/// <summary>
			/// 下载中
			/// </summary>
			Yes = 1,
		}

		/// <summary>
		/// 设置 是否需要更新 控制器状态
		/// </summary>
		public void SetController(EIsNeedUpgrade eIsNeedUpgrade) => IsNeedUpgrade.SetSelectedIndex((int) eIsNeedUpgrade);

		/// <summary>
		/// 设置 是否下载中 控制器状态
		/// </summary>
		public void SetController(EIsDownloading eIsDownloading) => IsDownloading.SetSelectedIndex((int) eIsDownloading);

        /// <summary>
        /// 界面组件初始化
        /// </summary>
        internal void InitUIComp()
        {
			IsNeedUpgrade = m_View.GetController("IsNeedUpgrade");
			IsDownloading = m_View.GetController("IsDownloading");
			txtTips = (GTextField)m_View.GetChild("_txtTips");
			progressBar = (GProgressBar)m_View.GetChild("_progressBar");
			btnOk = (GButton)m_View.GetChild("_btnOk");
			txtContent = (GRichTextField)m_View.GetChild("_txtContent");
        }
    }
}
