
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using GameFrameX.Core.Config;
using GameFrameX.Config;

namespace GameFrameX.Config
{
    public partial class TableManager
    {
        internal Local.TbLocalization TbLocalization { private set; get; }
        internal Tables.TbAchievement TbAchievement { private set; get; }
        internal Tables.TbItem TbItem { private set; get; }
        internal Tables.TbSound TbSound { private set; get; }
    
        private ConfigComponent m_ConfigComponent;

        public void Init(ConfigComponent configComponent)
        {
            m_ConfigComponent = configComponent;
            configComponent.RemoveAllConfigs();
        }

        public async System.Threading.Tasks.Task LoadAsync(System.Func<string, System.Threading.Tasks.Task<JsonElement>> loader)
        {
            //m_ConfigComponent.RemoveAllConfigs();
            var loadTasks = new System.Collections.Generic.List<System.Threading.Tasks.Task>();
    
            TbLocalization = new Local.TbLocalization(() => loader("local_tblocalization"));
            loadTasks.Add(TbLocalization.LoadAsync());
            m_ConfigComponent.Add(nameof(Local.TbLocalization), TbLocalization);

            TbAchievement = new Tables.TbAchievement(() => loader("tables_tbachievement"));
            loadTasks.Add(TbAchievement.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.TbAchievement), TbAchievement);

            TbItem = new Tables.TbItem(() => loader("tables_tbitem"));
            loadTasks.Add(TbItem.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.TbItem), TbItem);

            TbSound = new Tables.TbSound(() => loader("tables_tbsound"));
            loadTasks.Add(TbSound.LoadAsync());
            m_ConfigComponent.Add(nameof(Tables.TbSound), TbSound);

    
            await System.Threading.Tasks.Task.WhenAll(loadTasks);
    
            Refresh();
        }

        public TableManager()
        {
            //TablesMemory.BeginRecord();
    
            // TbLocalization = new Local.TbLocalization();
            // TbAchievement = new Tables.TbAchievement();
            // TbItem = new Tables.TbItem();
            // TbSound = new Tables.TbSound();
            //TablesMemory.EndRecord();
        }

        public void Refresh()
        {
            PostInit();
            ResolveRef();
        }

        private void ResolveRef()
        {
            TbLocalization.ResolveRef(this);
            TbAchievement.ResolveRef(this);
            TbItem.ResolveRef(this);
            TbSound.ResolveRef(this);
        }
    
        partial void PostInit();
    }
}
