
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace Hotfix.Config.Tables
{
    public sealed partial class Item : BeanBase
    {
        public Item(int Id, string Name, string Desc, string Icon, string Bg, EQuality Quality, ItemType Type, ItemSubType SubType, ItemUseType CanUse) 
        {
            this.Id = Id;
            this.Name = Name;
            this.Desc = Desc;
            this.Icon = Icon;
            this.Bg = Bg;
            this.Quality = Quality;
            this.Type = Type;
            this.SubType = SubType;
            this.CanUse = CanUse;
            PostInit();
        }

        public Item(JSONNode _buf)
        {
            { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
            { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
            { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
            { if(!_buf["icon"].IsString) { throw new SerializationException(); }  Icon = _buf["icon"]; }
            { if(!_buf["bg"].IsString) { throw new SerializationException(); }  Bg = _buf["bg"]; }
            { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = (EQuality)_buf["quality"].AsInt; }
            { if(!_buf["type"].IsNumber) { throw new SerializationException(); }  Type = (ItemType)_buf["type"].AsInt; }
            { if(!_buf["sub_type"].IsNumber) { throw new SerializationException(); }  SubType = (ItemSubType)_buf["sub_type"].AsInt; }
            { if(!_buf["can_use"].IsNumber) { throw new SerializationException(); }  CanUse = (ItemUseType)_buf["can_use"].AsInt; }

            // Localization Key Begin
            Name_Localization_Key = Name;
            Desc_Localization_Key = Desc;
            // Localization Key End
            PostInit();
        }

        public static Item DeserializeItem(JSONNode _buf)
        {
            return new Tables.Item(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 名称
        /// </summary>
        public string Name { private set; get; }
        /// <summary>
        /// 名称 的多语言Key
        /// </summary>
        private readonly string Name_Localization_Key;
        /// <summary>
        /// 描述
        /// </summary>
        public string Desc { private set; get; }
        /// <summary>
        /// 描述 的多语言Key
        /// </summary>
        private readonly string Desc_Localization_Key;
        /// <summary>
        /// 图标
        /// </summary>
        public string Icon { private set; get; }
        /// <summary>
        /// 背景图
        /// </summary>
        public string Bg { private set; get; }
        /// <summary>
        /// 品质
        /// </summary>
        public EQuality Quality { private set; get; }
        /// <summary>
        /// 类型
        /// </summary>
        public ItemType Type { private set; get; }
        /// <summary>
        /// 子类型
        /// </summary>
        public ItemSubType SubType { private set; get; }
        /// <summary>
        /// 能否使用
        /// </summary>
        public ItemUseType CanUse { private set; get; }
        public const int __ID__ = -1513240324;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            
            
            
            
            
            
        }

        public void TranslateText(System.Func<string, string, string> translator)
        {
            Name = translator(Name_Localization_Key, Name);
            Desc = translator(Desc_Localization_Key, Desc);
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "name:" + Name + ","
            + "desc:" + Desc + ","
            + "icon:" + Icon + ","
            + "bg:" + Bg + ","
            + "quality:" + Quality + ","
            + "type:" + Type + ","
            + "subType:" + SubType + ","
            + "canUse:" + CanUse + ","
            + "}";
        }

        partial void PostInit();
    }
}
