// <auto-generated>
//	本代码由FGUI插件CSharpAPIGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Launcher
{
    public partial class BootstrapView
    {
        private GComponent m_View;

		private Controller IsNeedUpgrade;
		private Controller IsDownloading;
		private GTextField txtTips;
		private GProgressBar progressBar;
		private GButton btnOk;
		private GRichTextField txtContent;

		/// <summary>
		/// IsNeedUpgrade 控制器状态枚举
		/// </summary>
		private enum EIsNeedUpgrade
		{
			/// <summary>
			/// No
			/// </summary>
			No = 0,
			/// <summary>
			/// Yes
			/// </summary>
			Yes = 1,
		}

		/// <summary>
		/// 设置 IsNeedUpgrade 控制器状态
		/// </summary>
		private void SetController(EIsNeedUpgrade eIsNeedUpgrade) => IsNeedUpgrade.SetSelectedIndex((int) eIsNeedUpgrade);

		/// <summary>
		/// IsDownloading 控制器状态枚举
		/// </summary>
		private enum EIsDownloading
		{
			/// <summary>
			/// No
			/// </summary>
			No = 0,
			/// <summary>
			/// Yes
			/// </summary>
			Yes = 1,
		}

		/// <summary>
		/// 设置 IsDownloading 控制器状态
		/// </summary>
		private void SetController(EIsDownloading eIsDownloading) => IsDownloading.SetSelectedIndex((int) eIsDownloading);


        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {
			IsNeedUpgrade = m_View.GetController("IsNeedUpgrade");
			IsDownloading = m_View.GetController("IsDownloading");
			txtTips = (GTextField)m_View.GetChild("_txtTips");
			progressBar = (GProgressBar)m_View.GetChild("_progressBar");
			btnOk = (GButton)m_View.GetChild("_btnOk");
			txtContent = (GRichTextField)m_View.GetChild("_txtContent");


        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {
			btnOk.onClick.Set(OnBtnOkClick);

        }
    }
}
