// <auto-generated>
//	Launcher 引导界面组件绑定代码（手动维护，结构与插件自动生成保持一致）。
//	UI 结构调整时只需修改此文件。
// </auto-generated>

using FairyGUI;

namespace Launcher
{
    public partial class BootstrapView
    {
        private GComponent     m_View;
        private Controller     m_IsNeedUpgrade;
        private Controller     m_IsDownloading;
        private GTextField     m_TxtTips;
        private GProgressBar   m_ProgressBar;
        private GButton        m_BtnOk;
        private GRichTextField m_TxtContent;

        /// <summary>
        /// 加载 FUI 包并创建 UI 组件。
        /// </summary>
        private void LoadUIPackage()
        {
            UIPackage.AddPackage("UI/Launcher/Launcher");

            m_View = UIPackage.CreateObject("Launcher", "WinLauncher").asCom;
            m_View.MakeFullScreen();
            GRoot.inst.AddChild(m_View);
        }

        /// <summary>
        /// 界面组件初始化。
        /// </summary>
        private void InitUIComp()
        {
            m_IsNeedUpgrade = m_View.GetController("IsNeedUpgrade");
            m_IsDownloading = m_View.GetController("IsDownloading");
            m_TxtTips       = (GTextField)m_View.GetChild("_txtTips");
            m_ProgressBar   = (GProgressBar)m_View.GetChild("_progressBar");
            m_BtnOk         = (GButton)m_View.GetChild("_btnOk");
            m_TxtContent    = (GRichTextField)m_View.GetChild("_txtContent");
        }

        /// <summary>
        /// 界面可交互组件事件初始化。
        /// </summary>
        private void InitUIEvent()
        {
            m_BtnOk.onClick.Set(OnBtnOkClick);
        }
    }
}
