
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using SimpleJSON;
using Hotfix.ModuleConfig;
namespace Hotfix.Config
{
    public partial class TableManager
    {

        /// <summary>
        /// 本地化多语言表
        /// </summary>
        internal Local.TbLocalization TbLocalization { private set; get; }

        /// <summary>
        /// 成就表
        /// </summary>
        internal Tables.TbAchievement TbAchievement { private set; get; }

        /// <summary>
        /// 道具表
        /// </summary>
        internal Tables.TbItem TbItem { private set; get; }

        /// <summary>
        /// 全局常量定义表
        /// </summary>
        internal Tables.TbGlobalDefine TbGlobalDefine { private set; get; }

        /// <summary>
        /// 声音表
        /// </summary>
        internal Tables.TbSound TbSound { private set; get; }

        private ConfigModule m_ConfigModule;

        public void Init(ConfigModule configModule)
        {
            m_ConfigModule = configModule;
            m_ConfigModule.RemoveAllConfigs();
        }

        /// <summary>
        /// 是否加载完成
        /// </summary>
        public bool IsLoaded { get; private set; }

        /// <summary>
        /// 异步加载配置文件
        /// </summary>
        /// <param name="loader">加载器</param>
        public async System.Threading.Tasks.Task LoadAsync(System.Func<string, System.Threading.Tasks.Task<JSONNode>> loader)
        {
            if (IsLoaded)
            {
                return;
            }
            IsLoaded = false;
            m_ConfigModule.RemoveAllConfigs();
            var loadTasks = new System.Collections.Generic.List<System.Threading.Tasks.Task>();
    
            TbLocalization = new Local.TbLocalization(() => loader("local_tblocalization"));
            loadTasks.Add(TbLocalization.LoadAsync());
            m_ConfigModule.AddConfig(nameof(Local.TbLocalization), TbLocalization);

            TbAchievement = new Tables.TbAchievement(() => loader("tables_tbachievement"));
            loadTasks.Add(TbAchievement.LoadAsync());
            m_ConfigModule.AddConfig(nameof(Tables.TbAchievement), TbAchievement);

            TbItem = new Tables.TbItem(() => loader("tables_tbitem"));
            loadTasks.Add(TbItem.LoadAsync());
            m_ConfigModule.AddConfig(nameof(Tables.TbItem), TbItem);

            TbGlobalDefine = new Tables.TbGlobalDefine(() => loader("tables_tbglobaldefine"));
            loadTasks.Add(TbGlobalDefine.LoadAsync());
            m_ConfigModule.AddConfig(nameof(Tables.TbGlobalDefine), TbGlobalDefine);

            TbSound = new Tables.TbSound(() => loader("tables_tbsound"));
            loadTasks.Add(TbSound.LoadAsync());
            m_ConfigModule.AddConfig(nameof(Tables.TbSound), TbSound);

    
            await System.Threading.Tasks.Task.WhenAll(loadTasks);
    
            Refresh();
            IsLoaded = true;
        }

        /// <summary>
        /// 设置本地化的适配器
        /// </summary>
        /// <param name="translator">适配器对象</param>
        /// <exception cref="InvalidOperationException">如果未加载完成将抛出此异常</exception>
        public void SetTranslateText(System.Func<string, string, string> translator)
        {
            if (IsLoaded == false)
            {
                throw new InvalidOperationException("Table is not loaded!");
            }
            TbLocalization.TranslateText(translator);
            TbAchievement.TranslateText(translator);
            TbItem.TranslateText(translator);
            TbGlobalDefine.TranslateText(translator);
            TbSound.TranslateText(translator);
        }

        private void ResolveRef()
        {
            TbLocalization.ResolveRef(this);
            TbAchievement.ResolveRef(this);
            TbItem.ResolveRef(this);
            TbGlobalDefine.ResolveRef(this);
            TbSound.ResolveRef(this);
        }
    
        public void Refresh()
        {
            PostInit();
            ResolveRef();
        }
    
        partial void PostInit();
    }
}
