services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./running/database:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    networks:
      - backend
  gameframex:
    image: gameframex/server.launcher:1.0.0
    container_name: gameframex
    ports:
      # APM 端口
      - "29090:29090"
      # TCP 端口
      - "29100:29100"
      # WebSocket 端口
      - "29110:29110"      
      # HTTP 端口
      - "28080:28080"
    environment:
      - ServerType=Game
      - ServerId=1000
      - APMPort=29090
      - InnerPort=29100
      - OuterPort=29100
      - MinModuleId=10
      - MaxModuleId=9999
      - WsPort=29110
      - HttpPort=28080
      - DiscoveryCenterIp=127.0.0.1
      - DiscoveryCenterPort=10001
      - HttpCode=inner_httpcode
      - DataBaseUrl=mongodb://admin:admin@mongodb:27017/?authSource=admin
      - DataBaseName=gameframex
    networks:
      - frontend
      - backend
    volumes:
      - "./running/hotfix:/app/hotfix"
      - "./running/json:/app/json"
      - "./running/logs:/app/logs"
      - "./running/GameAnalytics:/GameAnalytics"
networks:
  frontend:
    name: gameframex-frontend
    driver: bridge
  backend:
    name: gameframex-backend
    driver: bridge