
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using FuFramework.Core.Config;

namespace FuFramework.Config.Tables
{
    public sealed partial class Sound : BeanBase
    {
        /*
        public Sound(int Id, string GroupName, string Path, string Title, string CharacterName) 
        {
            this.Id = Id;
            this.GroupName = GroupName;
            this.Path = Path;
            this.Title = Title;
            this.CharacterName = CharacterName;
            PostInit();
        }        
        */

        public Sound(JsonElement _buf) 
        {
            Id = _buf.GetProperty("id").GetInt32();
            GroupName = _buf.GetProperty("groupName").GetString();
            Path = _buf.GetProperty("path").GetString();
            Title = _buf.GetProperty("title").GetString();
            CharacterName = _buf.GetProperty("characterName").GetString();
        }
    
        public static Sound DeserializeSound(JsonElement _buf)
        {
            return new Tables.Sound(_buf);
        }

        /// <summary>
        /// ID
        /// </summary>
        public int Id { private set; get; }
        /// <summary>
        /// 声音所属组
        /// </summary>
        public string GroupName { private set; get; }
        /// <summary>
        /// 声音所在的路径
        /// </summary>
        public string Path { private set; get; }
        /// <summary>
        /// 声音标题Key
        /// </summary>
        public string Title { private set; get; }
        public string CharacterName { private set; get; }

        private const int __ID__ = 343291974;
        public override int GetTypeId() => __ID__;

        public  void ResolveRef(TableManager tables)
        {
            
            
            
            
            
        }

        public override string ToString()
        {
            return "{ "
            + "id:" + Id + ","
            + "groupName:" + GroupName + ","
            + "path:" + Path + ","
            + "title:" + Title + ","
            + "characterName:" + CharacterName + ","
            + "}";
        }

        partial void PostInit();
    }
}
