
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Text.Json;
using FuFramework.Core.Config;

namespace FuFramework.Config.Tables
{
    public partial class TbItem : BaseDataTable<Tables.Item>
    {
        //private readonly System.Collections.Generic.Dictionary<int, Tables.Item> _dataMap;
        //private readonly System.Collections.Generic.List<Tables.Item> _dataList;
    
        //public System.Collections.Generic.Dictionary<int, Tables.Item> DataMap => _dataMap;
        //public System.Collections.Generic.List<Tables.Item> DataList => _dataList;
        //public Tables.Item GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
        //public Tables.Item Get(int key) => _dataMap[key];
        //public Tables.Item this[int key] => _dataMap[key];
    
        public override async System.Threading.Tasks.Task LoadAsync()
        {
            var jsonElement = await _loadFunc();
            DataList.Clear();
            LongDataMaps.Clear();
            StringDataMaps.Clear();
            foreach(var element in jsonElement.EnumerateArray())
            {
                Tables.Item _v;
                _v = Tables.Item.DeserializeItem(element);
                DataList.Add(_v);
                LongDataMaps.Add(_v.Id, _v);
                StringDataMaps.Add(_v.Id.ToString(), _v);
            }
            PostInit();
        }

        public void ResolveRef(TableManager tables)
        {
            foreach(var element in DataList)
            {
                element.ResolveRef(tables);
            }
        }
    
    
        partial void PostInit();

        public TbItem(Func<Task<JsonElement>> loadFunc) : base(loadFunc)
        {
        }
    }
}
