//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using SimpleJSON;
using Hotfix.Framework.Config;
using Cysharp.Threading.Tasks;

// ReSharper disable once CheckNamespace
namespace AOT.Launch.Localization
{
    public partial class TableManager
    {
        /// <summary> 热更前 </summary>
        private TbLocalizationAOT TbLocalizationAOT { set; get; }


        /// <summary> 是否加载完成 </summary>
        public bool IsLoaded { private set; get; }

        /// <summary> 框架配置模块 </summary>
        private ConfigModule m_ConfigModule;


        /// <summary>
        /// 初始化表管理器（关联配置模块并清空已有配置）
        /// </summary>
        /// <param name="configModule">配置管理模块</param>
        public void Init(ConfigModule configModule)
        {
            m_ConfigModule = configModule;
            m_ConfigModule.RemoveAllConfigs();
        }

        /// <summary>
        /// 异步加载全部配置表
        /// </summary>
        /// <param name="loader">取配置表 JSON 的加载委托</param>
        /// <returns>全部表加载完成</returns>
        /// <remarks>逐表建立、并行 await，全部完成后刷新引用</remarks>
        public async UniTask LoadAsync(Func<string, UniTask<JSONNode>> loader)
        {
            if (IsLoaded) return;

            IsLoaded = false;
            m_ConfigModule.RemoveAllConfigs();
            var loadTasks = new List<UniTask>();

            TbLocalizationAOT = new TbLocalizationAOT(() => loader("tblocalizationaot"));
            loadTasks.Add(TbLocalizationAOT.LoadAsync());
            m_ConfigModule.AddConfig(nameof(TbLocalizationAOT), TbLocalizationAOT);

            await UniTask.WhenAll(loadTasks);

            OnInit();
            ResolveRef();

            IsLoaded = true;
        }

        /// <summary>
        /// 解析所有配置表的跨表引用（表之间已加载完毕）
        /// </summary>
        private void ResolveRef()
        {
            TbLocalizationAOT.ResolveRef(this);
        }

        /// <summary>
        /// 为所有配置表设置本地化翻译器
        /// </summary>
        /// <param name="translator">翻译委托：传入 (key, original) 返回译文</param>
        /// <exception cref="InvalidOperationException">如果未加载完成将抛出此异常</exception>
        public void SetTranslateText(Func<string, string, string> translator)
        {
            if (IsLoaded == false) throw new InvalidOperationException("为配置表设置本地化翻译器失败，配置表没有被加载!");

            TbLocalizationAOT.TranslateText(translator);
        }

        /// <summary>
        /// 分部初始化钩子，由使用方补实现。
        /// 典型场景：完成一些所有配置表加载完成后的自定义预处理收尾工作
        /// </summary>
        partial void OnInit();
    }
}