// Copyright 2025 Code Philosophy
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

namespace Luban.CodeTarget;

public class CommonFileHeaders
{
    public const string AUTO_GENERATE_C_LIKE = @"//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且
//     如果重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
";


    public const string AUTO_GENERATE_LUA = @"
--[[------------------------------------------------------------------------------
-- <auto-generated>
--     此代码由工具生成。
--     对此文件的更改可能会导致不正确的行为，并且
--     如果重新生成代码，这些更改将会丢失。
-- </auto-generated>
--]]------------------------------------------------------------------------------
";

    public const string AUTO_GENERATE_PYTHON = @"
#-*- coding: utf-8 -*-
'''
  <auto-generated>
    此代码由工具生成。
    对此文件的更改可能会导致不正确的行为，并且
    如果重新生成代码，这些更改将会丢失。
  </auto-generated>
'''
";

    public const string AUTO_GENERATE_GDSCRIPT = @"
#  <auto-generated>
#    此代码由工具生成。
#    对此文件的更改可能会导致不正确的行为，并且
#    如果重新生成代码，这些更改将会丢失。
#  </auto-generated>
";

    public const string AUTO_GENERATE_PHP = @"<?php
";

    public const string AUTO_GENERATE_RUST = @"
/*!
<auto-generated>
    此代码由工具生成。
    对此文件的更改可能会导致不正确的行为，并且
    如果重新生成代码，这些更改将会丢失。
</auto-generated>
*/
";
}
