// <auto-generated>
//	本代码由FGUI插件CSharpCodeGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Hotfix.UI
{
    public partial class WinGlobalLoading
    {
        public override string UIName => "WinGlobalLoading";      // 界面名称
        public override string PackageName => "Common"; // 包名

		private Transition rotationAnim;



        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {
			rotationAnim = UIView.GetTransition("rotation");
        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {

        }
    }
}
