// <auto-generated>
//	本代码由FGUI插件CSharpAPIGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;
using UnityEngine;
using FuFramework.Core.Runtime;

namespace Hotfix.UI
{
    /// <summary>
    /// 自定义组件绑定器。
    /// 由FuiPackageManager加载包时自动反射调用。
    /// </summary>
    public class LoginBinder
    {
        /// <summary>
        /// 绑定所有自定义组件
        /// </summary>
        [RuntimeInitializeOnLoadMethod]
        public static void BindAll()
        {
            Log.Info("绑定包-{Login}下的所有自定义组件");
			UIObjectFactory.SetPackageItemExtension(CompPlayerListItem.URL, typeof(CompPlayerListItem));

        }
    }
}