// <auto-generated>
//	本代码由FGUI插件CSharpAPIGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Hotfix.UI.View.Login
{
    public partial class WinLoginAnnouncement
    {
        public override string UIName => "WinLoginAnnouncement";      // 界面名称
        public override string PackageName => "Login"; // 包名
        
		private GTextField txtTitle;
		private GRichTextField txtContent;

        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {
			txtTitle = (GTextField)GetChild("_txtTitle");
			txtContent = (GRichTextField)GetChild("_txtContent");


        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {

        }
    }
}
