// <auto-generated>
//	本代码由FGUI插件CSharpAPIGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Hotfix.UI.View.Login
{
    public partial class WinLogin
    {
        public override string UIName => "WinLogin";      // 界面名称
        public override string PackageName => "Login"; // 包名
        
		private GTextField txtLogin;
		private GTextField txtError;
		private GButton btnLogin;
		private GTextField txtUsername;
		private GTextInput inputUserName;
		private GTextField txtPassword;
		private GTextInput inputPassword;

        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {
			txtLogin = (GTextField)GetChild("_txtLogin");
			txtError = (GTextField)GetChild("_txtError");
			btnLogin = (GButton)GetChild("_btnLogin");
			txtUsername = (GTextField)GetChild("_txtUsername");
			inputUserName = (GTextInput)GetChild("_inputUserName");
			txtPassword = (GTextField)GetChild("_txtPassword");
			inputPassword = (GTextInput)GetChild("_inputPassword");


        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {
			AddUIListener(btnLogin.onClick, OnBtnLoginClick);
			AddUIListener(inputUserName.onChanged, OnInputUserNameChanged);
			AddUIListener(inputUserName.onFocusOut, OnInputUserNameFocusOut);
			AddUIListener(inputPassword.onChanged, OnInputPasswordChanged);
			AddUIListener(inputPassword.onFocusOut, OnInputPasswordFocusOut);

        }
    }
}
