// <auto-generated>
//	本代码由FGUI插件CSharpAPIGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Hotfix.UI.View.Login
{
    public partial class WinPlayerList
    {
        public override string UIName => "WinPlayerList";      // 界面名称
        public override string PackageName => "Login"; // 包名
        
		private enum ECtrlSelected
		{
			No = 0,
			Yes = 1,
		}

		private void SetController(ECtrlSelected eCtrlSelected) => CtrlSelected.SetSelectedIndex((int) eCtrlSelected);

		private Controller CtrlSelected;
		private GList listPlayer;
		private GLoader loaderSelectedIcon;
		private GRichTextField txtSelectedName;
		private GRichTextField txtSelectedLevel;
		private GButton btnLogin;

        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {
			CtrlSelected = UIView.GetController("CtrlSelected");
			listPlayer = (GList)GetChild("_listPlayer");
			loaderSelectedIcon = (GLoader)GetChild("_loaderSelectedIcon");
			txtSelectedName = (GRichTextField)GetChild("_txtSelectedName");
			txtSelectedLevel = (GRichTextField)GetChild("_txtSelectedLevel");
			btnLogin = (GButton)GetChild("_btnLogin");


        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {
			AddUIListener(listPlayer.onClickItem, OnClickListPlayerItem);
			AddUIListener(btnLogin.onClick, OnBtnLoginClick);
			listPlayer.itemRenderer = OnRenderListPlayerItem;

        }
    }
}
