// <auto-generated>
//	本代码由FGUI插件CSharpCodeGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;
using FairyGUI.Utils;

namespace Launcher
{
    public partial class CompBagItemInfoTest : GComponent
    {
		private Controller IsCanUse;
		private GTextField txtName;
		private GRichTextField txtDesc;

		public const string URL = "ui://u7deosq0dzni2v";

		/// <summary>
		/// 是否可使用
		/// </summary>
		private enum EIsCanUse
		{
			/// <summary>
			/// 不可使用
			/// </summary>
			No = 0,
			/// <summary>
			/// 可使用
			/// </summary>
			Yes = 1,
		}

		/// <summary>
		/// 设置 是否可使用 控制器状态
		/// </summary>
		private void SetController(EIsCanUse eIsCanUse) => IsCanUse.SetSelectedIndex((int) eIsCanUse);

		/// <summary>
		/// 组件被构造时由FUI自动调用
		/// </summary>
		/// <param name="xml">组件描述结构</param>
		public override void ConstructFromXML(XML xml)
		{
			base.ConstructFromXML(xml);
			InitUIComp();
		}

        /// <summary>
        /// 初始化（由外部在合适的时机调用）
        /// </summary>
        public void Init()
        {
            InitUIEvent();
            OnInit();
        }

        /// <summary>
        /// UI组件初始化
        /// </summary>
        private void InitUIComp()
        {
			IsCanUse = GetController("IsCanUse");
			txtName = (GTextField)GetChild("_txtName");
			txtDesc = (GRichTextField)GetChild("_txtDesc");
        }

        /// <summary>
        /// UI组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {

        }

        /// <summary>
        /// UI组件销毁
        /// </summary>
        public override void Dispose()
        {
            OnDispose();
            base.Dispose();
        }
    }
}
