// <auto-generated>
//	本代码由FGUI插件CSharpCodeGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Hotfix.Game.UI
{
    public partial class WinDialogMessageBox
    {
        public override string UIName => "WinDialogMessageBox";      // 界面名称
        public override string PackageName => "Tips"; // 包名

		private Controller BtnCtrl;
		private GRichTextField txtContent;
		private GButton btnOk;
		private GButton btnNo;

		/// <summary>
		/// 按钮显示状态
		/// </summary>
		private enum EBtnCtrl
		{
			/// <summary>
			/// 只显示取消按钮
			/// </summary>
			ShowAll = 3,
			/// <summary>
			/// 显示全部按钮
			/// </summary>
			HideAll = 0,
			/// <summary>
			/// 隐藏全部按钮
			/// </summary>
			ShowOk = 1,
			/// <summary>
			/// 只显示确认按钮
			/// </summary>
			ShowCancel = 2,
		}

		/// <summary>
		/// 设置 按钮显示状态 控制器状态
		/// </summary>
		private void SetController(EBtnCtrl eBtnCtrl) => BtnCtrl.SetSelectedIndex((int) eBtnCtrl);

        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {
			BtnCtrl = UIView.GetController("BtnCtrl");
			txtContent = (GRichTextField)GetChild("_txtContent");
			btnOk = (GButton)GetChild("_btnOk");
			btnNo = (GButton)GetChild("_btnNo");
        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {
			AddUIListener(btnOk.onClick, OnBtnOkClick);
			AddUIListener(btnNo.onClick, OnBtnNoClick);
        }
    }
}
