// <auto-generated>
//	本代码由FGUI插件CSharpAPIGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Hotfix.UI
{
    public partial class WinDialogMessageBox
    {
        public override string UIName => "WinDialogMessageBox";      // 界面名称
        public override string PackageName => "Tips"; // 包名
        
		private enum EBtnCtrl
		{
			ShowAll = 3,
			HideAll = 0,
			ShowOk = 1,
			ShowCancel = 2,
		}

		private void SetController(EBtnCtrl eBtnCtrl) => BtnCtrl.SetSelectedIndex((int) eBtnCtrl);

		private Controller BtnCtrl;
		private GRichTextField txtContent;
		private GButton btnOk;
		private GButton btnNo;

        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {
			BtnCtrl = UIView.GetController("BtnCtrl");
			txtContent = (GRichTextField)GetChild("_txtContent");
			btnOk = (GButton)GetChild("_btnOk");
			btnNo = (GButton)GetChild("_btnNo");


        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {
			AddUIListener(btnOk.onClick, OnBtnOkClick);
			AddUIListener(btnNo.onClick, OnBtnNoClick);

        }
    }
}
