<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><LangVersion>11</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FuFramework.SuperSocket.ProtoBase\FuFramework.SuperSocket.ProtoBase.csproj" />
  </ItemGroup>
</Project>
