// <auto-generated>
//	本代码由FGUI插件CSharpAPIGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Hotfix.UI
{
    public partial class WinLoadingScene
    {
        public override string UIName => "WinLoadingScene";      // 界面名称
        public override string PackageName => "Loading"; // 包名
        

        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {


        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {

        }
    }
}
