// <auto-generated>
//	本代码由FGUI插件CSharpAPIGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Launcher.UI
{
    public partial class WinLauncher
    {
        public override string UIName => "WinLauncher";      // 界面名称
        public override string PackageName => "Launcher"; // 包名
        
		private enum EIsNeedUpgrade
		{
			No = 0,
			Yes = 1,
		}

		private void SetController(EIsNeedUpgrade eIsNeedUpgrade) => IsNeedUpgrade.SetSelectedIndex((int) eIsNeedUpgrade);

		private enum EIsDownloading
		{
			No = 0,
			Yes = 1,
		}

		private void SetController(EIsDownloading eIsDownloading) => IsDownloading.SetSelectedIndex((int) eIsDownloading);

		private Controller IsNeedUpgrade;
		private Controller IsDownloading;
		private GTextField txtTips;
		private GProgressBar progressBar;
		private GButton btnOk;
		private GRichTextField txtContent;

        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {
			IsNeedUpgrade = UIView.GetController("IsNeedUpgrade");
			IsDownloading = UIView.GetController("IsDownloading");
			txtTips = (GTextField)GetChild("_txtTips");
			progressBar = (GProgressBar)GetChild("_progressBar");
			btnOk = (GButton)GetChild("_btnOk");
			txtContent = (GRichTextField)GetChild("_txtContent");


        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {
			AddUIListener(btnOk.onClick, OnBtnOkClick);

        }
    }
}
