<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><LangVersion>10</LangVersion></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FuFramework.SuperSocket.Server.Abstractions\FuFramework.SuperSocket.Server.Abstractions.csproj" />
  </ItemGroup>
</Project>
