// <auto-generated>
//	本代码由FGUI插件CSharpAPIGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Hotfix.UI.View.PopWin
{
    public partial class WinDialogWithoutButton
    {
        public override string UIName => "WinDialogWithoutButton";      // 界面名称
        public override string PackageName => "PopWin"; // 包名
        
		private GRichTextField txtContent;
		private GButton btnClose;

        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {
			txtContent = (GRichTextField)GetChild("_txtContent");
			btnClose = (GButton)GetChild("_btnClose");


        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {
			AddUIListener(btnClose.onClick, OnBtnCloseClick);

        }
    }
}
