<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><TargetFramework>net8.0</TargetFramework><LangVersion>10</LangVersion></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FuFramework.SuperSocket.Connection\FuFramework.SuperSocket.Connection.csproj" />
    <ProjectReference Include="..\FuFramework.SuperSocket.Primitives\FuFramework.SuperSocket.Primitives.csproj" />
    <ProjectReference Include="..\FuFramework.SuperSocket.ProtoBase\FuFramework.SuperSocket.ProtoBase.csproj" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.0" />
  </ItemGroup>
</Project>
