// <auto-generated>
//	本代码由FGUI插件CSharpAPIGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Hotfix.UI
{
    public partial class WinDialogGuide
    {
        public override string UIName => "WinDialogGuide";      // 界面名称
        public override string PackageName => "Guide"; // 包名
        
		private GTextField txtContent;
		private GButton btnNext;
		private GLoader loaderIcon;

        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {
			txtContent = (GTextField)GetChild("_txtContent");
			btnNext = (GButton)GetChild("_btnNext");
			loaderIcon = (GLoader)GetChild("_loaderIcon");


        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {
			AddUIListener(btnNext.onClick, OnBtnNextClick);

        }
    }
}
