// ------------------------------------------------------------------------------
// <auto-generated>
//     该类由红点配置SO自动导出，不可手动更改
// </auto-generated>
// ------------------------------------------------------------------------------

namespace Hotfix.UI
{
    /// <summary>
    /// 红点Key常量定义
    /// </summary>
    public static class RedDotKeys
    {
        public const string Bag = "Bag";
        public const string BagItem = "Bag.Item";
        public const string BagSkill = "Bag.Skill";

        public const string Shop = "Shop";
        public const string ShopGift = "Shop.Gift";
        public const string ShopRes = "Shop.Res";

        public const string Hero = "Hero";
        public const string HeroEquip = "Hero.Equip";
        public const string HeroSkill = "Hero.Skill";
        public const string HeroSkin = "Hero.Skin";

        public const string Battle = "Battle";
        public const string BattleTeam = "Battle.Team";
    }
}
