#if UNITY_EDITOR
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;
using UnityEditor;
using UnityEngine;
using FuFramework.ModuleSetting.Runtime;

// ReSharper disable once CheckNamespace
namespace FuFramework.ModuleSetting.Editor
{
    public partial class RedDotSettingEditor
    {
        /// <summary>
        /// 导出key常量定义静态类代码的路径
        /// </summary>
        private const string ExportPath = "Assets/Scripts/Hotfix/RedDot/RedDotKeys.cs";

        /// <summary>
        /// 保存配置
        /// </summary>
        private void SaveConfiguration()
        {
            // 1. 检查重复key和格式错误
            ForceRefreshValidationCheck();

            var hasErrors    = false;
            var errorMessage = "";

            // 检查格式错误
            if (m_InvalidFormatNodes.Count > 0)
            {
                hasErrors    =  true;
                errorMessage += $"发现 {m_InvalidFormatNodes.Count} 个格式错误的Key！\n";
            }

            // 检查重复key
            if (m_DuplicateKeyPaths.Count > 0)
            {
                hasErrors    =  true;
                errorMessage += $"发现 {m_DuplicateKeyPaths.Count} 个重复的Key！\n";
            }

            // 如果有错误，阻止保存并提示用户
            if (hasErrors)
            {
                errorMessage += "\n请先解决以上问题再保存！";
                EditorUtility.DisplayDialog("保存失败", errorMessage, "确定");
                return;
            }

            // 2. 应用修改并保存Asset
            serializedObject.ApplyModifiedProperties();
            EditorUtility.SetDirty(target);
            AssetDatabase.SaveAssets();

            // 3. 导出静态类
            ExportStaticClass();

            // 显示保存成功提示框
            EditorUtility.DisplayDialog("保存成功", "红点配置已保存并成功导出静态类代码！", "确定");
        }

        /// <summary>
        /// 收集所有唯一的key
        /// </summary>
        private HashSet<string> CollectAllUniqueKeys()
        {
            var setting = target as RedDotSetting;
            if (setting == null) return new HashSet<string>();

            var uniqueKeys = new HashSet<string>();

            // 递归收集所有key
            void CollectKeys(RedDotNodeData node)
            {
                if (node == null) return;

                if (!string.IsNullOrEmpty(node.m_Key))
                {
                    uniqueKeys.Add(node.m_Key);
                }

                foreach (var child in node.m_Children)
                {
                    CollectKeys(child);
                }
            }

            foreach (var rootNode in setting.m_RootNodes)
            {
                CollectKeys(rootNode);
            }

            return uniqueKeys;
        }

        /// <summary>
        /// 生成静态类代码
        /// </summary>
        private string GenerateStaticClassCode()
        {
            var uniqueKeys = CollectAllUniqueKeys();
            if (uniqueKeys.Count == 0)
            {
                Debug.LogWarning("没有找到任何Key，无法生成静态类");
                return string.Empty;
            }

            var sb = new StringBuilder();

            // 添加文件头注释
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("//     该类由红点配置SO自动导出，不可手动更改");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("// ------------------------------------------------------------------------------");
            sb.AppendLine();

            // 添加命名空间和类定义
            sb.AppendLine("namespace Hotfix.UI");
            sb.AppendLine("{");
            sb.AppendLine("    /// <summary>");
            sb.AppendLine("    /// 红点Key常量定义");
            sb.AppendLine("    /// </summary>");
            sb.AppendLine("    public static class RedDotKeys");
            sb.AppendLine("    {");

            // 按根节点分组key
            var setting = target as RedDotSetting;
            if (setting != null)
            {
                var rootNodeKeys = new List<List<string>>();

                // 收集每个根节点下的所有key
                foreach (var rootNode in setting.m_RootNodes)
                {
                    var keysInRoot = new List<string>();
                    CollectKeysFromNode(rootNode, keysInRoot);
                    if (keysInRoot.Count > 0)
                    {
                        rootNodeKeys.Add(keysInRoot.OrderBy(k => k).ToList());
                    }
                }

                // 按根节点分组输出，每组之间空一行
                for (var i = 0; i < rootNodeKeys.Count; i++)
                {
                    var keys = rootNodeKeys[i];
                    foreach (var key in keys)
                    {
                        // 确保key是有效的C#标识符
                        var validFieldName = MakeValidFieldName(key);
                        sb.AppendLine($"        public const string {validFieldName} = \"{key}\";");
                    }

                    // 如果不是最后一组，添加空行
                    if (i < rootNodeKeys.Count - 1)
                    {
                        sb.AppendLine();
                    }
                }
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");

            return sb.ToString();
        }

        /// <summary>
        /// 从节点收集所有key（递归）
        /// </summary>
        private void CollectKeysFromNode(RedDotNodeData node, List<string> keys)
        {
            if (node == null) return;

            if (!string.IsNullOrEmpty(node.m_Key))
            {
                keys.Add(node.m_Key);
            }

            foreach (var child in node.m_Children)
            {
                CollectKeysFromNode(child, keys);
            }
        }

        /// <summary>
        /// 将key转换为有效的C#字段名
        /// </summary>
        private string MakeValidFieldName(string key)
        {
            if (string.IsNullOrEmpty(key))
                return "EmptyKey";

            // 移除非法字符，只保留字母、数字和下划线
            var validName = new string(key.Where(c => char.IsLetterOrDigit(c) || c == '_').ToArray());

            // 如果以数字开头，添加前缀
            if (validName.Length > 0 && char.IsDigit(validName[0]))
            {
                validName = "Key_" + validName;
            }

            // 如果为空，使用默认名称
            if (string.IsNullOrEmpty(validName))
            {
                validName = "InvalidKey";
            }

            return validName;
        }

        /// <summary>
        /// 导出静态类代码到文件
        /// </summary>
        private void ExportStaticClass()
        {
            var code = GenerateStaticClassCode();
            if (string.IsNullOrEmpty(code))
            {
                Debug.LogError("生成静态类代码失败");
                return;
            }

            // 确定导出路径
            var directory = Path.GetDirectoryName(ExportPath);
            try
            {
                // 确保目录存在
                if (!Directory.Exists(directory) && directory != null)
                {
                    Directory.CreateDirectory(directory);
                }

                // 写入文件
                File.WriteAllText(ExportPath, code, Encoding.UTF8);

                // 刷新AssetDatabase
                AssetDatabase.Refresh();

                Debug.Log($"静态类已成功导出到: {ExportPath}");
            }
            catch (System.Exception ex)
            {
                Debug.LogError($"导出静态类失败: {ex.Message}");
            }
        }
    }
}
#endif