// <auto-generated>
//	本代码由FGUI插件CSharpCodeGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;

namespace Hotfix.Game.UI
{
    public partial class WinPlayerList
    {
        public override string WinName => "WinPlayerList";      // 界面名称
        public override string PackageName => "Login"; // 包名

		private Controller CtrlSelected;
		private GList listPlayer;
		private GLoader loaderSelectedIcon;
		private GRichTextField txtSelectedName;
		private GRichTextField txtSelectedLevel;
		private GButton btnLogin;

		/// <summary>
		/// 是否选中指定角色
		/// </summary>
		private enum ECtrlSelected
		{
			/// <summary>
			/// 没选中
			/// </summary>
			No = 0,
			/// <summary>
			/// 选中
			/// </summary>
			Yes = 1,
		}

		/// <summary>
		/// 设置 是否选中指定角色 控制器状态
		/// </summary>
		private void SetController(ECtrlSelected eCtrlSelected) => CtrlSelected.SetSelectedIndex((int) eCtrlSelected);

        /// <summary>
        /// 界面组件初始化
        /// </summary>
        private void InitUIComp()
        {
			CtrlSelected = WinUI.GetController("CtrlSelected");
			listPlayer = (GList)GetChild("_listPlayer");
			loaderSelectedIcon = (GLoader)GetChild("_loaderSelectedIcon");
			txtSelectedName = (GRichTextField)GetChild("_txtSelectedName");
			txtSelectedLevel = (GRichTextField)GetChild("_txtSelectedLevel");
			btnLogin = (GButton)GetChild("_btnLogin");
        }

        /// <summary>
        /// 界面可交互组件事件初始化
        /// </summary>
        private void InitUIEvent()
        {
			AddUIListener(listPlayer.onClickItem, OnClickListPlayerItem);
			AddUIListener(btnLogin.onClick, OnBtnLoginClick);
			listPlayer.itemRenderer = OnRenderListPlayerItem;
        }
    }
}
