// <auto-generated>
//	本代码由FGUI插件CSharpCodeGen自动生成. 切记不可手动更改!
// </auto-generated>
// ReSharper disable once CheckNamespace 禁用命名空间检查

using FairyGUI;
using UnityEngine;
using Hotfix.Framework.Core;
using AOT.Framework.Core.Log;

namespace Hotfix.Game.UI
{
    /// <summary>
    /// 所有自定义组件的绑定器。由FUI导出时自动生成。
    /// </summary>
    public static class CustomCompBind
    {
        /// <summary>
        /// 绑定所有自定义组件
        /// </summary>
        public static void BindAll()
        {
			BindBag();
			BindCommon();
			BindLogin();
        }

		/// <summary>
		/// 绑定Bag包下的自定义组件
		/// </summary>
		private static void BindBag()
		{
			FuLogger.LogInfo("绑定包-{Bag}下的所有自定义组件");
			UIObjectFactory.SetPackageItemExtension(CompGoodItem.URL, typeof(CompGoodItem));
			UIObjectFactory.SetPackageItemExtension(CompBagContent.URL, typeof(CompBagContent));
			UIObjectFactory.SetPackageItemExtension(CompBagItemInfo.URL, typeof(CompBagItemInfo));
			UIObjectFactory.SetPackageItemExtension(CompTypeItem.URL, typeof(CompTypeItem));
			UIObjectFactory.SetPackageItemExtension(CompBagItem.URL, typeof(CompBagItem));
		}

		/// <summary>
		/// 绑定Common包下的自定义组件
		/// </summary>
		private static void BindCommon()
		{
			FuLogger.LogInfo("绑定包-{Common}下的所有自定义组件");
			UIObjectFactory.SetPackageItemExtension(CompRedDot.URL, typeof(CompRedDot));
		}

		/// <summary>
		/// 绑定Login包下的自定义组件
		/// </summary>
		private static void BindLogin()
		{
			FuLogger.LogInfo("绑定包-{Login}下的所有自定义组件");
			UIObjectFactory.SetPackageItemExtension(CompPlayerListItem.URL, typeof(CompPlayerListItem));
		}
    }
}
